'use client';

import React, { useState } from 'react';

export default function FAQAccordion() {
  const [openSections, setOpenSections] = useState<{ [key: string]: boolean }>({});

  const toggleSection = (sectionId: string) => {
    setOpenSections((prev) => ({
      ...prev,
      [sectionId]: !prev[sectionId],
    }));
  };

  const faqSections = [
    {
      id: 'understanding',
      title: 'Understanding invoices',
      questions: [
        {
          q: 'What is an invoice and why is it important?',
          a: 'An invoice is a commercial document that records the sale of goods or services and requests payment. It lists the seller and buyer details, describes the goods or services provided, sets the price and any taxes, and states when payment is due. Invoices provide a transparent record of financial transactions, help track income and expenses and can be used to enforce payment obligations if disputes arise.',
        },
        {
          q: 'How is an invoice different from a receipt?',
          a: 'An invoice is issued before payment and acts as a demand for payment; a receipt is issued after payment and serves as proof that the money has been received.',
        },
        {
          q: 'What information should a standard invoice include in Nigeria?',
          a: 'A professional Nigerian invoice should include:\n\n• Your business name, address, contact information and logo.\n• The client\'s name and address.\n• A unique invoice number and the invoice date.\n• A clear description of the goods or services provided, quantities and unit prices.\n• Subtotals, any taxes (e.g., VAT) and the total amount owed.\n• Payment terms and due date.\n• Your bank account or mobile money details for payment.\n• Your Tax Identification Number (TIN) and VAT registration number if applicable.',
        },
        {
          q: 'When should I issue an invoice?',
          a: 'For normal business transactions you can issue an invoice immediately after delivering goods or completing a service. For VAT-registered businesses, the Value-Added Tax Act requires VAT invoices to be issued within fifteen days of the end of the month in which the supply occurred.',
        },
        {
          q: 'Do invoices in Nigeria need to be sequentially numbered?',
          a: 'Yes. Receipts and bills, which include invoices, must follow an unbroken sequential order starting from 1 at the beginning of each calendar year. Each cash register or invoicing system may have its own sequence but the numbers must not have gaps.',
        },
        {
          q: 'Are digital or electronic signatures accepted?',
          a: 'For paper invoices, signatures are optional. For electronic invoices under the Federal Inland Revenue Service (FIRS) e-invoicing system, each invoice must include a unique reference number, QR code and digital signature generated by the FIRS platform.',
        },
        {
          q: 'Can I edit an invoice after issuing it?',
          a: 'You can edit or void invoices that have not been paid. Once an invoice has been marked as paid, the record should not be altered. Instead, issue a credit note or a corrected invoice.',
        },
      ],
    },
    {
      id: 'vat-tax',
      title: 'VAT and tax requirements',
      questions: [
        {
          q: 'What is VAT and when must I register for it?',
          a: 'Value-Added Tax (VAT) is a 7.5% tax charged on most goods and services in Nigeria. Businesses with annual taxable turnover above ₦25 million must register for VAT, but businesses can also register voluntarily. Registration is usually done using FIRS\'s VAT form and requires a Tax Identification Number.',
        },
        {
          q: 'Do all invoices need VAT?',
          a: 'No. Only VAT-registered businesses need to include VAT on their invoices. Small businesses and freelancers that are not VAT-registered should issue normal invoices without VAT details.',
        },
        {
          q: 'What details must a VAT invoice contain?',
          a: 'A VAT invoice must show:\n\n• The invoice date.\n• A unique sequential number.\n• The supplier\'s name, address and VAT registration number.\n• The customer\'s name and address.\n• A description of the goods or services, quantities and unit price.\n• The VAT-exclusive amount, any discounts, the VAT rate and the total VAT payable.\n• The date the goods or services were supplied.\n\nThese requirements come from the VAT Act and ensure the buyer can claim input tax.',
        },
        {
          q: 'Can I invoice without a VAT number?',
          a: 'Yes. If you are not registered for VAT, you may issue invoices without a VAT number and without charging VAT. However, you cannot show a VAT amount on your invoice or imply that VAT is included.',
        },
        {
          q: 'Should I charge VAT if my business is not VAT-registered?',
          a: 'No. Businesses that include VAT on invoices without being registered are liable for a penalty up to 100% of the VAT amount shown.',
        },
        {
          q: 'What goods and services are exempt from VAT?',
          a: 'Certain items are exempt from VAT in Nigeria, including basic food items, books and educational materials, pharmaceuticals, baby products and exported goods.',
        },
        {
          q: 'When do I remit VAT to FIRS?',
          a: 'VAT invoices must be issued within 15 days after the end of the month of supply and VAT returns must be submitted and paid by the 21st day of the following month.',
        },
        {
          q: 'When should VAT returns be filed?',
          a: 'VAT returns (and payment of VAT collected) are due by the 21st day of every month.',
        },
      ],
    },
    {
      id: 'e-invoicing',
          title: 'E-invoicing & regulatory compliance',
      questions: [
        {
          q: 'What is e-invoicing and why is Nigeria adopting it?',
          a: 'Electronic invoicing (e-invoicing) is the creation and exchange of invoices in a structured digital format through a government-approved platform. Nigeria\'s Federal Inland Revenue Service (FIRS) is rolling out the Merchant Buyer Solution (MBS) e-invoicing system to improve tax compliance and transparency. Each e-invoice must contain a reference number, QR code and digital signature.',
        },
        {
          q: 'When will e-invoicing become mandatory?',
          a: 'According to FIRS guidelines, large taxpayers will be required to use the e-invoice clearance platform from July 2025. All businesses with turnover above ₦25 million and companies involved in import or export may be required to adopt e-invoicing, with full deployment expected by 2026.',
        },
        {
          q: 'Who must issue e-invoices?',
          a: 'Businesses with annual turnover above ₦25 million and those engaged in cross-border (import/export) transactions must register for e-invoicing. Smaller businesses are currently exempt, although the threshold may decrease in future.',
        },
        {
          q: 'What information is required on an e-invoice?',
          a: 'In addition to normal invoice details, e-invoices must include:\n\n• A unique invoice reference number and authentication code generated by FIRS.\n• A QR code that allows verification.\n• A digital signature to prove authenticity.\n\nBusinesses must authenticate each invoice on the FIRS portal before sending it to the buyer.',
        },
        {
          q: 'How do I register for e-invoicing?',
          a: 'Register on the FIRS e-invoice portal using your Tax Identification Number. You will need to integrate your accounting system with the portal or use approved software providers to generate and authenticate invoices.',
        },
        {
          q: 'Do I need to keep records of e-invoices?',
          a: 'Yes. Businesses are required to keep digital records of e-invoices and related documents for at least ten years.',
        },
        {
          q: 'Are electronic invoices legal in Nigeria?',
          a: 'Yes. Electronic invoices generated and authenticated through the FIRS platform are legally valid. They must contain the prescribed digital signature and reference number to be recognized for tax purposes.',
        },
      ],
    },
    {
      id: 'proforma',
      title: 'Proforma invoices & import questions',
      questions: [
        {
          q: 'What is a proforma invoice and when is it used?',
          a: 'A proforma invoice is a preliminary invoice issued by a supplier that gives an estimated description and price of goods before the actual shipment. In Nigeria, importers use proforma invoices to obtain Form M from the Nigeria Customs Service and the Central Bank of Nigeria before importing goods.',
        },
        {
          q: 'What information must a proforma invoice contain?',
          a: 'For import purposes, a proforma invoice should include:\n\n• The supplier\'s and buyer\'s names, addresses and contact details.\n• A unique invoice number and date.\n• Detailed description of each item, including quantity, HS code, unit price and total price.\n• Ancillary charges, such as packaging or local transport.\n• Country of origin and country of supply.\n• Mode of transport, origin and destination ports and freight cost.\n• Total cost (including cost and freight) and any terms of agreement.\n• Signature and stamp of the supplier.',
        },
        {
          q: 'Is a proforma invoice legally binding?',
          a: 'No. A proforma invoice is only an estimate; it is not a demand for payment and is not accepted by customs as proof of value. A commercial invoice must accompany the shipment and serves as the final document for customs.',
        },
        {
          q: 'How is a proforma invoice different from a commercial invoice?',
          a: 'A proforma invoice is used to provide a quotation and facilitate regulatory approvals (such as Form M). A commercial invoice is issued after the goods are ready for shipment and states the final value; it is accepted by customs and used for payment.',
        },
      ],
    },
    {
      id: 'payment',
      title: 'Payment and collections',
      questions: [
        {
          q: 'Why do clients sometimes fail to pay invoices in Nigeria?',
          a: 'Common reasons for unpaid invoices include:\n\n• Lack of a clear contract or written agreement.\n• Disputes about the quality or scope of work.\n• The client\'s inability to pay or cash-flow problems.',
        },
        {
          q: 'How can I reduce late payments or unpaid invoices?',
          a: 'To reduce unpaid invoices:\n\n• Discuss payment terms and budgets with clients before starting work and include them in a written contract.\n• Double-check invoice details (dates, amounts, client information) before sending.\n• Provide clear breakdowns of deliverables and payment schedules.\n• Offer professional customer service and maintain regular communication.\n• Follow up persistently; send reminders before and after the due date.\n• Include late-payment penalties or interest clauses where legally permissible.',
        },
        {
          q: 'What should I do if a client refuses to pay?',
          a: 'If a client does not pay, send a demand letter setting out the amount owed and a deadline for payment. If disputes persist, consider alternative dispute resolution (negotiation, mediation or arbitration) before taking legal action, as Nigerian courts encourage ADR for commercial disputes.',
        },
        {
          q: 'Can I charge interest on late payments?',
          a: 'The law allows parties to agree to late-payment interest in their contract. Include a clause on interest or penalties in your invoice terms. Ensure the rate complies with Nigerian contract law and is communicated up front.',
        },
        {
          q: 'What payment methods can I offer?',
          a: 'Invoices in Nigeria typically accept bank transfers. Many businesses also use payment gateways such as Paystack, Flutterwave or Interswitch to collect card payments or mobile money. For cross-border clients, consider platforms that support international payments (e.g., PayPal or Payoneer) subject to Central Bank rules.',
        },
      ],
    },
    {
      id: 'freelancer',
          title: 'Freelancer and gig-worker considerations',
      questions: [
        {
          q: 'What invoice elements are important for freelancers and gig workers?',
          a: 'Freelancers should include:\n\n• Their business name (or personal name) and contact details.\n• The client\'s information.\n• A unique invoice number, issue date and due date.\n• Clear description of services provided.\n• Payment terms (commonly 14–30 days).\n• Bank or mobile money details.\n• TIN and VAT number if registered.\n• Optional clauses for late payment fees and intellectual-property rights.',
        },
        {
          q: 'What currency should I invoice in?',
          a: 'If your client is in Nigeria, invoice in Nigerian Naira (₦). For international clients you may invoice in foreign currencies, but you should comply with Central Bank regulations on foreign exchange. Ensure the contract specifies the currency and conversion method.',
        },
        {
          q: 'Do freelancers need to register for VAT?',
          a: 'Freelancers must register for VAT once their turnover exceeds ₦25 million or if they choose to register voluntarily. Otherwise they should not include VAT on invoices.',
        },
        {
          q: 'What payment terms are common in Nigeria for freelancers?',
          a: 'Typical payment terms range from immediate payment on delivery (especially for small jobs) to 14 days or 30 days. Agree the due date in your contract to avoid misunderstandings.',
        },
      ],
    },
    {
      id: 'other',
      title: 'Other common questions',
      questions: [
        {
          q: 'Are invoices required for every sale?',
          a: 'Businesses should issue invoices or receipts for all taxable supplies. For VAT-registered businesses, issuing VAT invoices is mandatory so that buyers can claim input tax.',
        },
        {
          q: 'Do I need to include my Tax Identification Number (TIN) on invoices?',
          a: 'Yes. Nigerian businesses are encouraged to include their TIN and VAT registration number on invoices to ensure compliance and facilitate tax reporting.',
        },
        {
          q: 'How long should I keep invoice records?',
          a: 'Keep invoices and supporting documents for at least six years for tax purposes. For e-invoices, the FIRS requires businesses to keep records for at least ten years.',
        },
        {
          q: 'Can I issue invoices in foreign currency?',
          a: 'Yes, but you must follow Central Bank of Nigeria rules. For exports you may issue invoices in foreign currency; for domestic transactions you should normally use Naira. Always disclose the currency and exchange rate terms in your contract.',
        },
        {
          q: 'What is a credit note?',
          a: 'A credit note is a document issued to reduce or cancel part of an invoice—for example, when goods are returned or a discount is granted. It references the original invoice and shows the amount being credited.',
        },
      ],
    },
  ];

  return (
    <>
      {/* FAQ Accordion */}
      <div className="space-y-4">
        {faqSections.map((section) => (
          <div key={section.id} className="bg-white rounded-lg shadow">
            <button
              onClick={() => toggleSection(section.id)}
              className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
              <svg
                className={`w-5 h-5 text-gray-500 transition-transform ${
                  openSections[section.id] ? 'transform rotate-180' : ''
                }`}
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M19 9l-7 7-7-7"
                />
              </svg>
            </button>

            {openSections[section.id] && (
              <div className="px-6 pb-6 border-t border-gray-200">
                <div className="pt-4 space-y-6">
                  {section.questions.map((item, index) => (
                    <div key={index} className="border-b border-gray-100 last:border-b-0 pb-6 last:pb-0">
                      <h3 className="text-lg font-semibold text-gray-900 mb-2">{item.q}</h3>
                      <div className="text-gray-700 leading-relaxed whitespace-pre-line">
                        {item.a}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer Note */}
      <div className="mt-12 bg-blue-50 border border-blue-200 rounded-lg p-6">
        <p className="text-gray-800 leading-relaxed">
          This FAQ covers the most frequently asked questions about invoicing in Nigeria, combining 
          information from regulatory guidelines, tax rules and best practices. If you have more 
          questions, consult the Federal Inland Revenue Service (FIRS) or a qualified tax professional.
        </p>
      </div>
    </>
  );
}

