import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({
    connectionString,
    ssl: connectionString?.includes('supabase') ? { rejectUnauthorized: false } : undefined,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA (Article JSON-LD auto-generated by app/blog/[slug]/page.tsx)
//
// Post 1 — "Graphic Designer Invoice Template Nigeria"
//   Meta title : "Graphic Designer Invoice Template Nigeria | InvoiceGenerator.ng" (64 chars)
//   Meta desc  : "Create a professional graphic design invoice in Nigeria. Learn what to
//                 include, how to charge VAT at 7.5%, handle WHT, protect your
//                 files, and get paid on time." (156 chars)
//
// Post 2 — "How to Write a Quotation in Nigeria"
//   Meta title : "How to Write a Quotation in Nigeria | Template & Tips" (53 chars)
//   Meta desc  : "Learn how to write a professional business quotation in Nigeria.
//                 Includes what to include, VAT rules, validity periods, a free
//                 template, and how it differs from an invoice." (160 chars)
//
// Post 3 — "Late Payment Penalty Nigeria"
//   Meta title : "Late Payment Penalty Nigeria: Charge Interest on Overdue Invoices" (66 chars)
//   Meta desc  : "Nigerian businesses can legally charge interest on late invoices. Learn
//                 the correct rates, how to state payment terms, VAT on
//                 penalties, and how to enforce payment legally." (158 chars)
// ─────────────────────────────────────────────────────────────────────────────

const posts = [

    // =========================================================================
    // POST 1 — Graphic Designer Invoice Template Nigeria
    // Target keyword: "graphic designer invoice template Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'Graphic Designer Invoice Template Nigeria: What to Include & How to Get Paid',
        slug: 'graphic-designer-invoice-template-nigeria',
        excerpt: 'A complete guide for Nigerian graphic designers on creating professional invoices, charging VAT, protecting your work, and getting paid on time.',
        coverImage: null,
        published: true,
        content: `Graphic design is one of Nigeria's fastest-growing creative industries. From brand identity and social media content to packaging and UI/UX, designers are in high demand. But creative talent alone does not keep a business running — you also need to get paid reliably and professionally.

A well-structured invoice is your most important billing tool. This guide walks you through exactly what your graphic designer invoice should include, how to handle VAT, and how to protect yourself from late or non-payment.

## Why Graphic Designers Need Professional Invoices

Many Nigerian freelance designers still send informal payment requests over WhatsApp or email without a proper invoice document. This creates problems:

- Clients dispute what was agreed
- You have no paper trail for tax purposes
- Late payments are harder to chase without a formal document
- You appear less professional, which affects your rates

A proper invoice signals that you run a serious business — and it protects both you and your client.

## Mandatory Elements on a Nigerian Graphic Design Invoice

Under FIRS guidelines, every commercial invoice in Nigeria should include:

### 1. Your Business Information
- Full name or business name (e.g., "Kola Designs Ltd" or "Amaka Obi — Freelance Designer")
- Business address
- Phone number and email
- **Tax Identification Number (TIN)** — required if you are VAT-registered

### 2. Client Information
- Client's full name or company name
- Client's address and contact details
- Client's TIN (if they are a registered business)

### 3. Invoice Details
- **Unique invoice number** — e.g., KD-2026-041
- **Invoice date**
- **Due date** — typically 7, 14, or 30 days from invoice date

### 4. Itemised Services
Break down your work clearly. Do not just write "Design Services — ₦150,000." Instead:

| Description | Qty | Unit Price | Amount |
|---|---|---|---|
| Brand identity design (logo, colour palette, typography) | 1 | ₦120,000 | ₦120,000 |
| Business card design (print-ready files) | 1 | ₦25,000 | ₦25,000 |
| Brand style guide (PDF) | 1 | ₦35,000 | ₦35,000 |
| **Subtotal** | | | **₦180,000** |
| **VAT (7.5%)** | | | **₦13,500** |
| **Total** | | | **₦193,500** |

### 5. Payment Details
- Bank name, account number, account name
- Or a Paystack payment link for instant online payment

### 6. Terms and Conditions
- Late payment policy (e.g., 5% monthly interest on overdue balances)
- Revision limits included in the project
- IP/copyright ownership terms

---

## Do Graphic Designers in Nigeria Charge VAT?

**Yes, if your annual turnover exceeds ₦25 million**, you are legally required to register for VAT with FIRS and charge 7.5% VAT on your services.

If your turnover is below this threshold, VAT registration is optional — but you still cannot charge VAT unless you are registered. Charging VAT without a FIRS registration number is a compliance violation.

**Withholding Tax (WHT)** is also relevant for designers working with corporate clients. Companies are required to deduct 5% WHT from payments to individuals and 5% from payments to corporate service providers. Your client will deduct this and issue you a WHT credit note, which you can offset against your annual income tax.

**Practical example:**

You invoice a Lagos agency ₦200,000 + VAT:
- Invoice total: ₦215,000
- WHT deducted by client (5% of ₦200,000): ₦10,000
- Amount client pays you: ₦205,000
- WHT credit note: ₦10,000 (usable against your tax bill)

---

## Pricing Models for Nigerian Graphic Designers

Your invoice structure depends on how you price your work:

### Project-Based Pricing
A fixed fee for a defined deliverable. Best for logo design, packaging, brochures.

*Example: Logo + brand guidelines = ₦150,000 flat*

### Hourly Rate
Charge per hour of work. Suitable for ongoing design work or projects with unclear scope.

*Example: ₦8,000/hour × 20 hours = ₦160,000*

### Retainer
A monthly fee for a set number of hours or deliverables. Ideal for social media content.

*Example: 20 social media posts per month = ₦120,000/month*

### Value-Based Pricing
Price based on the value you deliver, not time spent. Advanced strategy for senior designers.

---

## Protecting Your Work Before Payment

### Deposit Policy
Always collect a **50% deposit** before starting work. This is standard practice in the Nigerian creative industry and protects you from scope creep and abandoned projects.

Structure your invoices as:
1. **Deposit invoice** — 50% upfront before work begins
2. **Balance invoice** — 50% on delivery or before final files are released

### File Release
Only release full-resolution, print-ready, or editable source files (AI, PSD, Figma) after full payment. You can send low-resolution watermarked previews for approval.

State this clearly in your invoice terms: *"Source files and high-resolution exports will be released upon receipt of full payment."*

---

## How to Send Your Invoice

**WhatsApp** is the dominant business communication channel in Nigeria. Most clients expect to receive invoices via WhatsApp alongside email. Send a PDF invoice — never a screenshot or informal message.

**[InvoiceGenerator.ng](https://www.invoicegenerator.ng/)** lets you create a professional, itemised invoice in minutes, add your logo, calculate VAT automatically, and share it directly via WhatsApp or email. No spreadsheets or manual PDF formatting needed.

---

## Getting Paid on Time

Late payment is a persistent challenge for Nigerian creative professionals. Here is how to reduce it:

1. **Set clear due dates** — "Payment due 7 days from invoice date" is better than "Payment due soon"
2. **Send a reminder 2 days before the due date** — a simple WhatsApp message works
3. **Charge late fees** — state in your terms that overdue invoices attract 5% monthly interest
4. **Use Paystack** — a payment link on your invoice makes it easy for clients to pay instantly via card or bank transfer
5. **Stop work on overdue retainers** — do not continue delivering work if the previous month's invoice is unpaid

---

## Invoice Checklist for Nigerian Graphic Designers

Before sending any invoice, confirm:

- [ ] Invoice number is unique and sequential
- [ ] Invoice date and due date are correct
- [ ] Services are itemised (not bundled into one line)
- [ ] VAT is correctly calculated at 7.5% (if registered)
- [ ] Your TIN is shown (if VAT-registered)
- [ ] Bank details are accurate
- [ ] Payment terms and file release policy are stated
- [ ] PDF is professionally formatted with your logo

---

## Create Your Free Graphic Design Invoice

Stop sending informal payment requests. Use **[InvoiceGenerator.ng](https://www.invoicegenerator.ng/)** to create a professional graphic design invoice in under 2 minutes — with automatic VAT calculation, Paystack integration, and WhatsApp sharing built in.

Also see our complete **[Nigerian Invoicing Guide](/guide)** for more on VAT registration, FIRS compliance, and best practices for freelancers.`,
    },

    // =========================================================================
    // POST 2 — How to Write a Quotation in Nigeria
    // Target keyword: "how to write a quotation in Nigeria"  (~1,100 words)
    // =========================================================================
    {
        title: 'How to Write a Quotation in Nigeria: Template, Tips & Key Differences from an Invoice',
        slug: 'how-to-write-a-quotation-in-nigeria',
        excerpt: 'A step-by-step guide to writing professional business quotations in Nigeria — what to include, how to format them, and when a quotation becomes an invoice.',
        coverImage: null,
        published: true,
        content: `A quotation (or quote) is often the first formal document exchanged in a business deal. It tells your potential client what you will deliver, at what price, and under what terms — before any work begins. In Nigeria, writing a professional quotation can be the difference between winning and losing a contract.

This guide covers everything you need to know: what belongs in a Nigerian business quotation, how to format it correctly, and how it differs from an invoice.

## What Is a Business Quotation?

A **quotation** is a formal price offer from a supplier or service provider to a potential buyer. It is not a request for payment — that comes later on an invoice. A quotation simply says: *"Here is what I will do and what it will cost you."*

When a client accepts your quotation (verbally, by email, or by signing it), it becomes a binding agreement. That is why the wording and terms in your quotation matter.

**Other terms you may see used interchangeably:**
- Quote
- Price proposal
- Cost estimate (less formal — does not imply a fixed price)
- Proforma invoice (a quotation formatted like an invoice — see our [proforma invoice guide](/blog/proforma-invoice-nigeria-what-it-is))

---

## Quotation vs Invoice: Key Differences

| | Quotation | Invoice |
|---|---|---|
| **Purpose** | Price offer before work begins | Request for payment after work is done |
| **Timing** | Sent before the job | Sent after delivery |
| **Payment obligation** | No payment due yet | Payment is due |
| **Document number** | Quote number (e.g., Q-2026-012) | Invoice number (e.g., INV-2026-041) |
| **Validity** | Usually 14–30 days | Due within agreed terms |
| **VAT** | Should show estimated VAT | Must show actual VAT if registered |

---

## What to Include in a Nigerian Business Quotation

### 1. Your Business Details
- Business name, address, phone, email
- TIN (Tax Identification Number) — especially important for B2B quotations
- RC number if your business is registered with CAC

### 2. Client Details
- Company name, contact person, address
- Reference to their RFQ (Request for Quotation) number if applicable

### 3. Quotation Number and Date
- Assign a unique number: e.g., Q-2026-015
- Include the date the quote was prepared
- State the **validity period**: "This quotation is valid for 14 days from the date above"

### 4. Itemised Description of Goods or Services
Be specific. Vague descriptions lead to scope disputes later.

**Good example:**
| Item | Description | Qty | Unit Price | Total |
|---|---|---|---|---|
| Website Design | 5-page responsive website (Home, About, Services, Portfolio, Contact) | 1 | ₦450,000 | ₦450,000 |
| Domain Registration | .com.ng domain, 1 year | 1 | ₦12,000 | ₦12,000 |
| Web Hosting | cPanel shared hosting, 1 year | 1 | ₦35,000 | ₦35,000 |
| **Subtotal** | | | | **₦497,000** |
| **VAT (7.5%)** | | | | **₦37,275** |
| **Total** | | | | **₦534,275** |

**Bad example:**
> Website work — ₦500,000

### 5. Payment Terms
- Deposit required (e.g., 50% upfront)
- Balance due on delivery or within X days of completion
- Accepted payment methods: bank transfer, Paystack, etc.

### 6. Delivery / Completion Timeline
State when you will deliver. For services: "Work to commence within 5 working days of deposit receipt and be completed within 3 weeks."

### 7. Terms and Conditions
Keep these concise but cover:
- What is **excluded** from the price
- Revision/amendment policy
- What happens if scope changes
- Cancellation policy

### 8. Authorisation
For formal B2B quotations, include a signature line:

> *Prepared by: [Name], [Title]*
> *Signature: _______________*
> *Date: _______________*

Some companies also ask clients to sign and return the quotation as acceptance.

---

## Quotation Validity and Price Escalation

Always state how long your quote is valid. Prices for labour, materials, and foreign-currency software tools change — especially in Nigeria's volatile economy. A quotation with no expiry date could leave you locked into a price that no longer makes commercial sense.

**Recommended validity periods:**
- Services (design, consulting, software): 14–30 days
- Construction and supply: 7–14 days (materials prices fluctuate)
- Long-term contracts: price review clause after 3–6 months

Include this clause for USD-priced services: *"Prices are quoted in Naira at the exchange rate of ₦[X]/$1. Significant currency movement may require a revised quotation."*

---

## VAT on Nigerian Quotations

If you are VAT-registered with FIRS (annual turnover above ₦25 million), you must include VAT at 7.5% on your quotation. Show it as a separate line item — do not roll it into the total and hide it.

If you are not VAT-registered, do not include VAT on your quotation. Charging VAT without a valid FIRS registration number is a compliance violation.

---

## How to Send a Quotation in Nigeria

Most Nigerian businesses communicate over **WhatsApp and email**. Best practice:

1. Prepare your quotation as a **PDF** — never a raw Word document or screenshot
2. Send via **email** for formal clients; follow up on **WhatsApp**
3. Reference the quote number in all follow-up messages
4. Set a calendar reminder to follow up if you have not heard back within 3 days

---

## From Quotation to Invoice

Once your client accepts the quotation:

1. Reference the quote number on your invoice (e.g., "Re: Quotation Q-2026-015")
2. The invoice amount should match the accepted quotation (unless scope changed)
3. If scope changed, issue a **variation order** or **amended quotation** before proceeding — do not just change the invoice amount without documentation

Use **[InvoiceGenerator.ng](https://www.invoicegenerator.ng/)** to quickly convert an accepted quotation into a professional invoice with VAT, payment terms, and a Paystack payment link — all in one place.

---

## Free Quotation Template for Nigerian Businesses

Here is a simple text format you can adapt:

---

**QUOTATION**
**[Your Business Name]**
[Address] | [Phone] | [Email] | TIN: [Your TIN]

**Quotation No:** Q-2026-XXX
**Date:** [Date]
**Valid Until:** [Date + 14 days]

**Prepared for:**
[Client Name / Company]
[Client Address]

| Description | Qty | Unit Price (₦) | Total (₦) |
|---|---|---|---|
| [Service/Product] | | | |
| Subtotal | | | |
| VAT (7.5%) | | | |
| **TOTAL** | | | |

**Payment Terms:** 50% deposit. Balance due on delivery.
**Bank Details:** [Bank] | [Account Number] | [Account Name]

*This quotation is valid for 14 days. Prices exclude any costs not listed above.*

---

For a complete guide to invoicing in Nigeria including FIRS requirements, VAT compliance, and payment terms, see our **[Nigerian Invoicing Guide](/guide)**.`,
    },

    // =========================================================================
    // POST 3 — Late Payment Penalty Nigeria
    // Target keyword: "late payment penalty Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'Late Payment Penalty Nigeria: Can You Charge Interest on Overdue Invoices?',
        slug: 'late-payment-penalty-nigeria-interest-on-overdue-invoices',
        excerpt: 'Yes — Nigerian businesses can legally charge interest and penalties on overdue invoices. Here is how to do it correctly, what rates to use, and how to enforce payment.',
        coverImage: null,
        published: true,
        content: `Late payment is one of the biggest financial challenges facing Nigerian freelancers, SMEs, and contractors. A client who delays payment by 30, 60, or 90 days effectively gets an interest-free loan at your expense. The good news: you have the legal right to charge interest on overdue invoices — and doing so professionally can significantly improve your cash flow.

This guide explains the legal basis, how to calculate late payment interest, and practical steps to enforce your payment terms in Nigeria.

## Can You Legally Charge Interest on Late Invoices in Nigeria?

**Yes.** Under Nigerian contract law, parties are free to agree on penalty clauses and interest charges for late payment. The relevant legal frameworks include:

- **The Contracts Act** — late payment interest is enforceable if agreed in writing
- **FIRS invoicing requirements** — do not prohibit late payment charges; they simply require proper documentation
- **Common law principles** — courts recognise contractual interest provisions

The key requirement is that the late payment terms must be **stated in your contract or invoice before work begins**. You cannot add a late payment penalty after the fact without prior agreement.

---

## How to State Your Late Payment Terms

Your payment terms should appear in two places:

### 1. Your Contract or Service Agreement
Include a clause such as:

> *"Invoices are due within [14/30] days of issue date. Overdue invoices will attract interest at [2–5]% per month (or part thereof) on the outstanding balance until paid in full."*

### 2. Your Invoice
Add a "Payment Terms" section at the bottom of every invoice:

> *"Payment due: [specific date]. Overdue balances attract interest at 3% per month."*

When both the contract and invoice clearly state this, it is fully enforceable.

---

## What Interest Rate Can You Charge?

Nigerian law does not set a fixed maximum late payment interest rate for commercial contracts — parties are free to agree. However, courts may reduce a rate they consider "unconscionable" (grossly unfair). Common rates used in the Nigerian market:

| Rate | Context |
|---|---|
| 2% per month | Conservative — suits long-standing client relationships |
| 3–5% per month | Standard for Nigerian freelancers and SMEs |
| 10%+ per month | High — may be reduced by a court if disputed |
| CBN MPR + spread | Used in formal financial agreements |

**Practical example:**

You issued an invoice for ₦500,000 due on 1 February 2026. The client pays on 1 April 2026 — 60 days (2 months) late. At 3% per month:

- Interest: ₦500,000 × 3% × 2 months = **₦30,000**
- Total payable: **₦530,000**

---

## Types of Late Payment Charges

### Percentage Interest (Most Common)
A monthly percentage on the outstanding balance. Compounds if unpaid for multiple months.

### Fixed Late Fee
A flat fee added once the invoice becomes overdue. Simple to administer but less deterrent for large invoices.

*Example: "A flat fee of ₦5,000 will be added to invoices not paid within 30 days."*

### Stop-Work Clause
Not a monetary penalty, but highly effective: state that work will be suspended on overdue accounts. This is particularly useful for retainer clients.

*Example: "InvoiceGenerator.ng reserves the right to suspend services where invoices remain unpaid beyond 14 days of the due date."*

---

## VAT on Late Payment Interest

If you are VAT-registered, be aware: **FIRS requires VAT at 7.5% on late payment interest charges** when billed to a VAT-able client. Issue a separate invoice or debit note for the interest amount, and include VAT.

*Example:*
- Late payment interest: ₦30,000
- VAT (7.5%): ₦2,250
- **Total debit note: ₦32,250**

---

## How to Enforce Late Payment in Nigeria

### Step 1: Formal Payment Reminder
Send a written reminder (WhatsApp + email) the day after the due date. Reference the invoice number and due date. Keep the tone professional.

*Template:*
> *"Dear [Client], this is a reminder that Invoice No. INV-2026-041 for ₦[Amount] was due on [Date] and remains unpaid. Please arrange payment at your earliest convenience. Interest of [X]% per month applies to overdue balances as per our agreed terms."*

### Step 2: Late Payment Notice
If unpaid after 7 days, send a formal Late Payment Notice restating the penalty terms and calculating the interest accrued so far.

### Step 3: Demand Letter
After 14–21 days, send a formal demand letter (signed, on letterhead) demanding payment of the original invoice plus accrued interest within 7 days, failing which you will pursue the matter legally.

### Step 4: Small Claims Court or Arbitration
For amounts up to ₦5 million, Nigeria's **Small Claims Courts** (available in Lagos, Abuja, Rivers, and other states) offer a fast-track resolution process without needing a lawyer. Filing fees are low and judgments can be obtained in days or weeks rather than years.

For larger amounts or where the contract specifies arbitration, the **Lagos Court of Arbitration** or **Lagos Multi-Door Courthouse** offer alternative dispute resolution.

### Step 5: Report to Credit Bureaus
Nigerian credit bureaus (CRC, FirstCentral, CreditRegistry) allow businesses to report non-paying commercial debtors. This affects the debtor's credit score and their ability to access financing — a powerful incentive for settlement.

---

## Preventing Late Payment Before It Happens

The best late payment strategy is prevention:

1. **Collect a deposit upfront** — 30–50% before starting work eliminates the worst-case scenario
2. **Use milestone invoicing** — break large projects into payment stages tied to deliverables
3. **Make payment easy** — include a Paystack link on every invoice so clients can pay instantly by card or bank transfer
4. **Send invoices immediately** — do not wait until the end of the month; invoice on delivery
5. **Know your client** — do a basic credit check on new corporate clients; ask for trade references

---

## Create Invoices with Payment Terms Built In

**[InvoiceGenerator.ng](https://www.invoicegenerator.ng/)** lets you add your custom payment terms, late payment interest clause, and due date to every invoice — professionally formatted and ready to send via WhatsApp or email.

For more on Nigerian invoicing best practices, see our **[complete invoicing guide](/guide)** and our post on **[invoice payment terms Nigeria](/blog/invoice-payment-terms-nigeria)**.`,
    },
];

async function main() {
    console.log(`Seeding batch 5 blog posts (${posts.length} posts)...\n`);

    const author = await prisma.user.findFirst({
        where: { email: 'adebayoadesokan@gmail.com' },
    });

    if (!author) {
        throw new Error('Author not found. Check the email address.');
    }

    console.log(`Author: ${author.name} (${author.email})\n`);

    for (const post of posts) {
        const result = await prisma.blogPost.upsert({
            where: { slug: post.slug },
            update: { ...post, authorId: author.id },
            create: { ...post, authorId: author.id },
        });
        console.log(`✅  ${result.title}`);
        console.log(`    /blog/${result.slug}\n`);
    }

    console.log(`Done — ${posts.length} posts live.`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
        await pool.end();
    });
