import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({
    connectionString,
    ssl: connectionString?.includes('supabase') ? { rejectUnauthorized: false } : undefined,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA (Article JSON-LD auto-generated by app/blog/[slug]/page.tsx)
//
// Post 1 — "How to Invoice as a Lawyer in Nigeria"
//   Meta title : "How to Invoice as a Lawyer in Nigeria | InvoiceGenerator.ng" (59 chars)
//   Meta desc  : "How Nigerian lawyers and legal practitioners should structure
//                 invoices: billing rates, VAT on legal services, retainer fees,
//                 and FIRS compliance requirements." (157 chars)
//
// Post 2 — "Invoice Templates for Nigerian SMEs"
//   Meta title : "Invoice Templates for Nigerian SMEs | InvoiceGenerator.ng" (57 chars)
//   Meta desc  : "The best invoice templates for Nigerian small businesses and SMEs:
//                 what to include, how to format for FIRS compliance, and where
//                 to generate them for free." (154 chars)
//
// Post 3 — "Contractor Invoicing Guide Nigeria"
//   Meta title : "Contractor Invoicing Guide Nigeria | InvoiceGenerator.ng" (56 chars)
//   Meta desc  : "How Nigerian building contractors should invoice for labour,
//                 materials, and phased construction projects — with VAT,
//                 retention fees, and FIRS compliance tips." (157 chars)
// ─────────────────────────────────────────────────────────────────────────────

const posts = [

    // =========================================================================
    // POST 1 — How to Invoice as a Lawyer in Nigeria
    // Target keyword: "how to invoice as a lawyer Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'How to Invoice as a Lawyer in Nigeria',
        slug: 'how-to-invoice-as-a-lawyer-nigeria',
        excerpt: 'How Nigerian lawyers and legal practitioners should structure invoices: billing rates, VAT on legal services, retainer fees, and FIRS compliance requirements.',
        coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Legal practice in Nigeria is as much a business as it is a profession. Yet many Nigerian lawyers — from solo practitioners in Ibadan to partners at Lagos law firms — still use informal billing methods: handwritten receipts, voice notes with bank details, or Word documents with no invoice number.

Professional invoicing matters for lawyers not just for cash flow, but for compliance. Legal fees are subject to specific FIRS rules, and an incorrectly structured invoice can create VAT liability problems for both you and your clients.

This guide covers how to structure your invoices correctly as a Nigerian legal practitioner.

## Is VAT Applicable on Legal Services in Nigeria?

Yes. Legal services are taxable supplies under Nigeria's Value Added Tax Act. If your law firm or chambers has an annual taxable turnover of **₦25 million or more**, you must:

- Register for VAT with FIRS
- Add VAT at **7.5%** to your fees on every invoice
- Include your VAT registration number on all tax invoices
- Remit collected VAT to FIRS by the 21st of the following month

Lawyers below the ₦25 million threshold are not required to charge VAT. However, many sole practitioners voluntarily register — particularly those advising corporate clients who prefer to claim input VAT credits.

**Practical note:** If you are instructed by a company that is VAT-registered, they will ask for a proper tax invoice. A handwritten receipt means they cannot reclaim the VAT they paid you — and they will find a lawyer who issues proper invoices.

## Withholding Tax on Legal Fees

In addition to VAT, legal fees paid by a **company** to a lawyer are subject to **Withholding Tax (WHT)** at **10%**. Your corporate clients are required by law to deduct 10% WHT from your invoice amount before remitting payment, and they must issue you a WHT credit note.

**Example:**
> Invoice: Professional legal retainer — March 2026
> Fee: ₦500,000
> VAT (7.5%): ₦37,500
> **Invoice total: ₦537,500**
>
> Client deducts WHT (10% on fee, excluding VAT): ₦50,000
> **Amount remitted to lawyer: ₦487,500**
> WHT credit note: ₦50,000 (you use this to offset your income tax liability)

Always issue your invoice for the full amount including VAT. The WHT deduction is the client's obligation — you do not reduce your invoice by WHT.

## The Correct Structure for a Nigerian Legal Invoice

### Header

Your invoice header should contain:

> **[YOUR FIRM NAME]**
> Solicitors & Advocates | Barristers & Solicitors
> [Address] | TIN: [your TIN] | VAT Reg: [your VAT registration number]
>
> **TAX INVOICE**
> Invoice No: INV-2026-[sequential number]
> Date: [invoice date] | Due: [due date]
>
> Bill To: [Client name, address, and TIN]

### Fee Items

List every chargeable item clearly. Legal invoices typically include:

| Service | Units | Rate | Amount |
|---|---|---|---|
| Retainer — March 2026 | 1 month | ₦300,000 | ₦300,000 |
| Court appearance — Federal High Court, Lagos (3 Apr) | 1 | ₦80,000 | ₦80,000 |
| Legal research and brief preparation | 6 hrs | ₦15,000/hr | ₦90,000 |
| Review and negotiation of commercial lease | 1 | ₦120,000 | ₦120,000 |
| **Subtotal** | | | **₦590,000** |
| **VAT (7.5%)** | | | **₦44,250** |
| **Total Due** | | | **₦634,250** |

### Disbursements

Disbursements (filing fees, court fees, stamp duties, travel costs) are generally charged at cost, without VAT markup, though this depends on your firm's policy. List them separately:

> Filing fee — Lagos High Court Registry: ₦15,000 (disbursement, no VAT)

### Notes Section

> "Payment due within [14/30] days. WHT deductions must be accompanied by a credit note. All fees are exclusive of out-of-pocket disbursements unless itemised above. For queries, contact accounts@[yourfirm].ng."

## Billing Models and How to Invoice for Each

### Hourly Billing

The most transparent model. Invoice on a monthly basis or at the conclusion of a matter.

> 12.5 hours × ₦18,000/hr = ₦225,000 + VAT (₦16,875) = **₦241,875**

Keep time records to support every hourly invoice — clients may request a breakdown.

### Fixed Fee (Matter-Based)

One fee for the entire matter (e.g., company incorporation, contract drafting). Invoice either fully upfront or split: 50% on instruction, 50% on completion.

> Company registration and CAC filing — fixed fee: ₦180,000 + VAT = **₦193,500**

### Retainer

A monthly fee for ongoing access to legal advice. Issue the retainer invoice on the same date each month (e.g., 1st of month) with due date Net 7 or Net 14.

> Monthly legal retainer — April 2026: ₦400,000 + VAT (₦30,000) = **₦430,000**
> Due: 8 April 2026

### Contingency Fee

If your fee is contingent on the outcome (e.g., a percentage of damages awarded), invoice only when the outcome is achieved. Note the basis of the fee clearly:

> Contingency fee — 15% of ₦4,200,000 damages awarded (Suit No. FHC/L/2025/1234): ₦630,000 + VAT = **₦677,250**

## Payment Terms for Legal Practices

- **Retainers:** Due on receipt or Net 7 — retainers fund ongoing work and should not be outstanding
- **Transactional matters:** 50% on instruction, 50% on completion
- **Litigation:** 50% upfront, milestone invoices at key stages (filing, hearing, judgment)
- **Corporate clients:** Net 30 is often their AP cycle; factor this into your pricing

Always include a **late payment clause**: *"A fee of 2% per month applies on invoices outstanding beyond the due date."*

## Common Mistakes to Avoid

- **No TIN on the invoice** — mandatory for all formal business transactions in Nigeria since the Finance Act 2020
- **Not separating VAT from fees** — VAT must appear as a distinct line item so corporate clients can claim it
- **Charging WHT on your own invoice** — WHT is deducted by the client, not added by you
- **Using informal receipts for corporate clients** — they need a proper tax invoice for their own compliance
- **No sequential numbering** — FIRS requires unbroken invoice sequences

## Generate Compliant Legal Invoices Instantly

[InvoiceGenerator.ng](/invoice-generator-nigeria) includes all the fields a Nigerian lawyer needs: TIN, VAT registration number, sequential invoice numbering, automatic VAT calculation, and professional PDF output. For a full explanation of Nigerian invoicing requirements and VAT rules, visit the [invoicing guide](/guide).

---

*Issue professional, FIRS-compliant legal invoices in under two minutes — free at [InvoiceGenerator.ng](/invoice-generator-nigeria).*`,
    },

    // =========================================================================
    // POST 2 — Invoice Templates for Nigerian SMEs
    // Target keyword: "invoice template for small business Nigeria"  (~1,000 words)
    // =========================================================================
    {
        title: 'Invoice Templates for Nigerian SMEs',
        slug: 'invoice-templates-nigerian-smes',
        excerpt: 'The best invoice templates for Nigerian small businesses and SMEs: what to include, how to format for FIRS compliance, and where to generate them for free.',
        coverImage: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `A good invoice template is the backbone of a well-run Nigerian small business. The right template means you spend two minutes creating each invoice rather than twenty, you never forget a mandatory field, and every document you send looks professional enough to be taken seriously.

This guide covers what every Nigerian SME invoice template should include, the different types you might need, and where to get them for free.

## Why Template Quality Matters for Nigerian SMEs

Most Nigerian small businesses start with an informal approach: a Word document, a WhatsApp message, or a handwritten receipt book. This works until it doesn't — until a corporate client requires a proper tax invoice, FIRS asks for records during an audit, or a payment dispute arises and you have no documented paper trail.

A well-designed template solves all of this. It standardises your billing, makes you look credible to larger clients, and ensures you meet FIRS requirements automatically.

## What Every Nigerian SME Invoice Template Must Include

Regardless of your industry, every invoice template should have these sections:

### Your Business Header

- Business name (as registered with CAC)
- Trading address
- Phone number and email
- Your logo (builds brand recognition and professionalism)
- TIN (mandatory since Finance Act 2020)
- VAT registration number (if VAT-registered with annual turnover ≥ ₦25 million)

### Invoice Identifiers

- The label **"Invoice"** or **"Tax Invoice"** at the top
- A unique sequential **invoice number** (e.g., INV-2026-001)
- **Invoice date** — the date of issue
- **Due date** — when payment is expected

### Client Details

- Client or company name
- Client address
- Client TIN (for B2B transactions — enables them to claim input VAT)

### Itemised Services or Products

A table with:
- Description of each item or service
- Quantity
- Unit price
- Line total

### Totals Section

- Subtotal (before tax)
- VAT at 7.5% (if VAT-registered) — shown as a separate line
- **Total Amount Due** — bold and prominent

### Payment Details

- Bank name
- Account name (matching your registered business name)
- NUBAN account number
- Paystack or payment gateway link (if used)

### Terms and Notes

- Payment due date (restate it here)
- Late payment clause: *"A fee of 2% per month applies after the due date"*
- Any relevant project notes or thank-you message

## Templates by Business Type

### Service Business Template (Consultants, Creatives, Trainers)

Service businesses bill for time or deliverables. Your template needs a flexible line-item table where you can describe intangible outputs clearly.

**Sample line items:**
> Brand identity package — ₦250,000
> Social media content calendar (April 2026) — ₦85,000
> 3 × revision rounds — ₦0 (included)

**Subtotal: ₦335,000 | VAT: ₦25,125 | Total: ₦360,125**

### Product/Goods Template (Retailers, Suppliers, Manufacturers)

Product invoices need columns for SKU or product code, quantity, unit price, and line total. If you sell a mix of VAT-exempt and taxable goods, the template must support per-line VAT tagging.

**Sample line items:**
> Carton of mineral water (24 × 75cl) — 10 cartons × ₦4,200 = ₦42,000 *(exempt)*
> Industrial cleaning supplies — 5 units × ₦8,500 = ₦42,500 *(taxable)*
> VAT on taxable items (7.5%): ₦3,188

### Retainer/Subscription Template

For businesses billing recurring monthly fees. The template includes the billing period, the fixed fee, and a note that the next invoice will follow on the same date next month.

> Monthly IT support retainer — April 2026: ₦120,000
> Billing period: 1–30 April 2026
> Next invoice due: 1 May 2026

### Milestone/Project Template

For large projects billed in phases. Each invoice references the project name and the specific milestone being invoiced.

> Project: Greenfield Office Fit-Out — Phase 2 (Electrical Works)
> Invoice #INV-2026-014 of 3
> Milestone amount: ₦800,000 + VAT (₦60,000) = **₦860,000**
> Balance remaining after this invoice: ₦1,400,000

## Common Template Mistakes to Avoid

**No invoice number** — this is the most common mistake. Every invoice needs a sequential number. FIRS requires it; your accountant needs it; your client's AP team will ask for it if it is missing.

**Mixing personal and business account details** — your invoice payment account must match your registered business name. Clients (especially corporates) flag mismatches and may delay payment pending verification.

**Forgetting the due date** — "pay when convenient" is not a payment term. State the exact date.

**Vague service descriptions** — "Professional services — ₦500,000" invites queries and disputes. Describe what was delivered specifically.

**No VAT breakdown** — if you are VAT-registered, embedding the VAT in the total (rather than showing it as a line item) means your client cannot claim input credit.

## Free vs Paid Templates: What Nigerian SMEs Need

Most Nigerian SMEs do not need a paid invoicing solution. A free tool that generates clean, branded, FIRS-compliant invoices is sufficient for most businesses under ₦50 million in annual turnover.

What to look for in a free template tool:

- **Naira (₦) support** — the default currency should be NGN, not USD
- **TIN field** — must be included as a visible field on the invoice
- **Automatic VAT calculation** — enter 7.5% once and let it calculate
- **Sequential numbering** — the tool should track and auto-increment invoice numbers
- **PDF download** — professional PDF output, not a browser print screenshot
- **WhatsApp sharing** — send directly to clients without switching apps

[InvoiceGenerator.ng](/invoice-generator-nigeria) provides all of the above free of charge, with templates designed specifically for Nigerian SMEs. No sign-up required for basic use.

For a full guide to what every Nigerian invoice must contain and how FIRS compliance works, visit the [InvoiceGenerator.ng invoicing guide](/guide).

---

*Generate a professional Nigerian SME invoice in under two minutes — free at [InvoiceGenerator.ng](/invoice-generator-nigeria).*`,
    },

    // =========================================================================
    // POST 3 — Contractor Invoicing Guide Nigeria
    // Target keyword: "contractor invoicing Nigeria"  (~1,100 words)
    // =========================================================================
    {
        title: 'Contractor Invoicing Guide Nigeria',
        slug: 'contractor-invoicing-guide-nigeria',
        excerpt: 'How Nigerian building contractors should invoice for labour, materials, and phased construction projects — with VAT, retention fees, and FIRS compliance tips.',
        coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Construction and contracting in Nigeria involves some of the most complex invoicing scenarios of any industry. A single project may span months, involve multiple subcontractors, include materials and labour on the same invoice, carry retention deductions, and require progress billing at each stage.

Get your invoicing wrong and you risk delayed payments, VAT disputes, and problems during project audits. This guide covers exactly how Nigerian contractors — from small building firms to large civil engineering companies — should structure their invoices.

## How VAT Works on Construction Invoices in Nigeria

Construction services are **taxable supplies** under the VAT Act. If your contracting business has annual taxable turnover of **₦25 million or more**, you must:

- Register for VAT and charge **7.5%** on taxable supplies
- Include your VAT registration number on every tax invoice
- Remit collected VAT to FIRS by the 21st of the following month

### VAT on Materials vs Labour

This is where many Nigerian contractors get confused. The general rule:

- **Labour supplied as a service** — taxable at 7.5%
- **Building materials** — taxable at 7.5% (most building materials are not VAT-exempt)
- **Land and bare buildings** — exempt from VAT
- **Supply and installation together** — taxable at 7.5% on the combined value

If you are supplying both materials and labour on a single contract (the most common scenario), apply VAT at 7.5% to the entire amount.

**Example:**
> Bricklaying and block supply, Phase 1:
> Materials: ₦380,000
> Labour: ₦220,000
> Subtotal: ₦600,000
> VAT (7.5%): ₦45,000
> **Total: ₦645,000**

## Withholding Tax on Contractor Payments

When a **company** pays a contractor, the company is required by law to withhold tax:

- **WHT on construction work:** 5%
- **WHT on professional or consulting services:** 10%

This means your corporate client will deduct 5% WHT from your invoice amount and remit it to FIRS on your behalf, issuing you a WHT credit note. Always invoice for the full amount — do not pre-deduct WHT on your own invoice.

**Example:**
> Invoice total: ₦645,000
> WHT deducted by client (5%): ₦30,000 *(on the pre-VAT subtotal of ₦600,000)*
> **Amount remitted to contractor: ₦615,000**
> WHT credit note to contractor: ₦30,000

Keep all WHT credit notes. They offset your corporate income tax liability at year-end.

## Progress Invoicing: Billing by Construction Phase

Most Nigerian construction contracts are billed progressively — in stages tied to project milestones rather than in one lump sum at the end.

### Setting Up Progress Invoices

Each progress invoice should:
- Clearly identify the project name and contract reference
- State which phase or milestone is being invoiced (e.g., "Phase 2 — Roofing Works")
- Show the **cumulative amount billed** and the **balance remaining on the contract**
- Reference the original contract value

**Example — three-phase residential project (Contract value: ₦12,000,000):**

**Invoice 1 — Mobilisation and Foundation:**
> Contract: Gwarinpa Residential Duplex — Block A
> Contract value: ₦12,000,000
> Phase 1 (Mobilisation + Foundation): ₦3,600,000
> VAT (7.5%): ₦270,000
> **Invoice 1 Total: ₦3,870,000**
> Cumulative billed: ₦3,600,000 | Remaining: ₦8,400,000

**Invoice 2 — Superstructure and Roofing:**
> Phase 2 (Block-work, Lintels, Roof): ₦4,800,000
> VAT (7.5%): ₦360,000
> **Invoice 2 Total: ₦5,160,000**
> Cumulative billed: ₦8,400,000 | Remaining: ₦3,600,000

**Invoice 3 — Finishes and Handover:**
> Phase 3 (Plastering, Tiling, Electrical, Painting): ₦3,600,000
> VAT (7.5%): ₦270,000
> **Invoice 3 Total: ₦3,870,000**
> Cumulative billed: ₦12,000,000 | Remaining: ₦0

## Handling Retention

Retention is a percentage of your invoice amount (commonly 5–10%) that the client holds back until the defects liability period expires — typically 12 months after project completion.

### How to Show Retention on Invoices

Show the gross amount, then deduct retention as a line item before the total payable:

> Phase 2 Works: ₦4,800,000
> VAT (7.5%): ₦360,000
> Gross Invoice: ₦5,160,000
> Less: Retention (5% on pre-VAT amount): **(₦240,000)**
> **Net amount payable now: ₦4,920,000**
> Retention balance held: ₦240,000

**Note on VAT and retention:** FIRS position is that VAT is due on the full taxable supply at the time of supply, not just the net-of-retention amount. Invoice for the full VAT amount; the retention deduction is a commercial arrangement, not a VAT adjustment.

### Releasing Retention

When the defects liability period ends, issue a **Retention Release Invoice**:

> Retention Release — Gwarinpa Duplex Block A
> Retention held from Invoices 1–3: ₦600,000
> VAT previously invoiced on this amount: ₦0 *(VAT was invoiced upfront)*
> **Amount due on retention release: ₦600,000**

## Variation Orders

When work is added or removed from the original contract scope, issue a **Variation Order Invoice** referencing the variation order number and the original contract:

> Variation Order #3 — Additional retaining wall (approved 14 Mar 2026)
> Works: ₦280,000
> VAT (7.5%): ₦21,000
> **Variation Invoice Total: ₦301,000**
> Ref: Contract GWA-2026-01, VO #3

Never perform variation work without a signed variation order first. The signed VO is your authority to invoice for it.

## The Mandatory Fields Checklist for Contractor Invoices

Before sending any invoice, verify:

- [ ] Labelled "Tax Invoice" (if VAT-registered)
- [ ] Your registered company name and address
- [ ] RC number and TIN
- [ ] VAT registration number (if applicable)
- [ ] Unique sequential invoice number
- [ ] Invoice date and payment due date
- [ ] Client name, address, and TIN
- [ ] Project name and contract reference
- [ ] Phase/milestone description
- [ ] Labour and materials itemised separately where possible
- [ ] Subtotal, VAT (7.5%), and total
- [ ] Retention deduction (if applicable)
- [ ] Cumulative billed and contract balance remaining
- [ ] Your bank details

For the full breakdown of FIRS invoice requirements and how VAT applies across different supply types, see the [InvoiceGenerator.ng invoicing guide](/guide).

## Create Contractor Invoices Instantly

[InvoiceGenerator.ng](/invoice-generator-nigeria) generates FIRS-compliant invoices with all mandatory fields — TIN, VAT calculation, sequential numbering, and notes sections for retention and project references. Download as PDF or send directly via WhatsApp to your client's project manager.

---

*Invoice professionally on every project — try the free [Nigerian invoice generator](/invoice-generator-nigeria) today.*`,
    },
];

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    console.log('Seeding batch 4 blog posts (3 posts)...\n');

    let author = await prisma.user.findFirst({ where: { isAdmin: true } });
    if (!author) {
        console.log('No admin user found — checking for any user...');
        author = await prisma.user.findFirst();
    }
    if (!author) {
        console.error('❌  No users found. Please sign up in the app first.');
        process.exit(1);
    }

    if (author.name !== 'Olivia S') {
        author = await prisma.user.update({
            where: { id: author.id },
            data: { name: 'Olivia S' },
        });
    }

    console.log(`Author: ${author.name} (${author.email})\n`);

    for (const post of posts) {
        const result = await prisma.blogPost.upsert({
            where: { slug: post.slug },
            update: { ...post, authorId: author.id },
            create: { ...post, authorId: author.id },
        });
        console.log(`✅  ${result.title}`);
        console.log(`    /blog/${result.slug}\n`);
    }

    console.log('Done — 3 posts live.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
        await pool.end();
    });
