import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({
    connectionString,
    ssl: connectionString?.includes('supabase') ? { rejectUnauthorized: false } : undefined,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA (for reference — schema is auto-generated by blog/[slug]/page.tsx)
// ─────────────────────────────────────────────────────────────────────────────
//
// Post 1 — "FIRS Invoice Requirements Nigeria 2026"
//   Meta title  : "FIRS Invoice Requirements Nigeria 2026 | InvoiceGenerator.ng" (60 chars)
//   Meta desc   : "Everything Nigerian businesses need to know about FIRS invoice
//                  requirements in 2026: mandatory fields, TIN rules, VAT at 7.5%,
//                  and penalties for non-compliance." (160 chars)
//
// Post 2 — "Send Invoices via WhatsApp in Nigeria"
//   Meta title  : "Send Invoices via WhatsApp in Nigeria | InvoiceGenerator.ng" (59 chars)
//   Meta desc   : "A step-by-step guide to sending professional invoices via WhatsApp
//                  in Nigeria. Practical tips for freelancers and small businesses
//                  to get paid faster." (150 chars)
//
// Post 3 — "Invoice vs Receipt in Nigeria"
//   Meta title  : "Invoice vs Receipt in Nigeria | InvoiceGenerator.ng" (51 chars)
//   Meta desc   : "What is the difference between an invoice and a receipt in Nigeria?
//                  Learn the legal distinctions, when to use each, and what FIRS
//                  requires from businesses." (155 chars)
//
// Article JSON-LD schema is injected automatically by app/blog/[slug]/page.tsx
// ─────────────────────────────────────────────────────────────────────────────

const posts = [

    // =========================================================================
    // POST 1 — FIRS Invoice Requirements Nigeria 2026
    // Target keyword: "FIRS invoice requirements Nigeria 2026"  (~1,500 words)
    // =========================================================================
    {
        title: 'FIRS Invoice Requirements Nigeria 2026',
        slug: 'firs-invoice-requirements-nigeria-2026',
        excerpt: 'Everything Nigerian businesses need to know about FIRS invoice requirements in 2026: mandatory fields, TIN rules, VAT at 7.5%, and penalties for non-compliance.',
        coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Every Nigerian business that issues invoices — whether you are a sole trader in Kano, a tech startup in Yaba, or a consulting firm in Victoria Island — needs to understand what the Federal Inland Revenue Service (FIRS) now requires on every invoice. Getting it wrong does not just look unprofessional; it can attract penalties, block your clients from claiming input VAT, and put your business at risk during a tax audit.

This guide covers every mandatory field, explains how VAT at 7.5% applies, and walks through the consequences of non-compliance. For a broader overview of invoicing in Nigeria, visit our [complete Nigerian invoicing guide](/guide).

## What Is a FIRS-Compliant Invoice?

A FIRS-compliant invoice is a formal document that meets the requirements of the Value Added Tax Act (Cap V1, LFN 2004 as amended), the Finance Act 2020, and subsequent FIRS guidelines. For VAT-registered businesses, a compliant invoice is the only document that allows your buyer to claim input VAT credit. For all businesses, it is the primary record used by FIRS to verify transactions during audits.

Consider this: if your client pays ₦500,000 for a project and cannot reclaim the ₦35,156 VAT on that invoice because the invoice is non-compliant, they will look for a supplier who issues correct invoices. A compliant invoice is therefore a competitive advantage.

## Mandatory Fields on Every Nigerian Invoice

### 1. The Word "Invoice" or "Tax Invoice"

The document must be clearly labelled as an **Invoice** or **Tax Invoice**. This distinguishes it from a receipt, quotation, or delivery note. VAT-registered businesses should use "Tax Invoice."

### 2. Your Registered Business Name and Address

Use your business name exactly as it appears with the Corporate Affairs Commission (CAC). Include your physical or registered office address. A P.O. Box alone is not sufficient.

**Example:**
> Bright Solutions Limited
> 14 Adetokunbo Ademola Crescent, Wuse 2, Abuja

### 3. Tax Identification Number (TIN)

This is non-negotiable. Since the Finance Act 2020, every business entity in Nigeria must include its **TIN on all invoices**. Your TIN is issued by FIRS and can be verified at the FIRS TIN portal.

- Sole traders and freelancers must include their personal TIN
- Format: typically an 8-digit number (e.g., \`12345678-0001\`)
- If you do not yet have a TIN, register at FIRS.gov.ng before issuing formal invoices

### 4. VAT Registration Number

If your business turnover exceeds **₦25 million per year**, you must be VAT-registered and include your VAT registration number on every tax invoice. Businesses below this threshold do not charge VAT but may register voluntarily.

### 5. Unique Sequential Invoice Number

Every invoice must carry a **unique, non-repeating invoice number** that follows an unbroken sequence within the calendar year. FIRS uses invoice sequences to detect gaps that may indicate unreported transactions.

**Recommended format:** INV-2026-001, INV-2026-002, INV-2026-003…

If you cancel an invoice, issue a credit note against it — never recycle the invoice number.

### 6. Invoice Date

The date on which the invoice is issued. For VAT invoices, FIRS requires that the invoice be issued **within 15 days of the end of the month** in which the supply took place.

**Example:** A web design project completed on 18 March 2026 must have its tax invoice issued no later than 15 April 2026.

### 7. Client Name and Address

Include the full legal name and address of the buyer. For B2B transactions, also include the client's TIN — this enables them to claim input VAT and is increasingly required by large corporates and government agencies.

### 8. Description of Goods or Services

Be specific. FIRS auditors expect a clear description of what was supplied.

**Weak:** "Consultancy Services — ₦300,000"
**Strong:** "Digital marketing strategy and Q1 2026 campaign planning (Jan–Mar 2026, three months) — ₦300,000"

Vague descriptions are a common trigger for invoice disputes and audit queries.

### 9. Quantity and Unit Price

List each item or service with its quantity and unit price. For projects with multiple deliverables, itemise each line separately.

| Description | Qty | Unit Price | Line Total |
|---|---|---|---|
| Logo design | 1 | ₦150,000 | ₦150,000 |
| Brand style guide | 1 | ₦80,000 | ₦80,000 |
| Business card design | 2 | ₦25,000 | ₦50,000 |
| **Subtotal** | | | **₦280,000** |

### 10. VAT at 7.5%

Nigeria's VAT rate is **7.5%** under the Finance Act 2019. Show it as a separate line item on every tax invoice.

**Example:**
> Subtotal: ₦280,000
> VAT (7.5%): ₦21,000
> **Total Due: ₦301,000**

Exempt items — basic food, books, pharmaceuticals, and educational materials — do not attract VAT. If an invoice mixes taxable and exempt items, calculate VAT only on the taxable lines.

### 11. Total Amount Due

Display the final payable amount clearly, in figures:
> **Total Due: ₦301,000**

### 12. Payment Details

Include your:
- Bank name
- Account name (must match your registered business name)
- NUBAN account number
- Payment gateway link (Paystack, Flutterwave) if available

## The E-Invoicing Mandate: What Has Changed

FIRS has been rolling out the **Merchant Buyer Solution (MBS)**, Nigeria's national e-invoicing framework. Under MBS:

- B2B invoices above specified thresholds require digital validation through a FIRS-accredited Access Point Provider
- Validated invoices receive a unique **Invoice Reference Number (IRN)** and a QR code
- Buyers can verify authenticity by scanning the QR code

If you supply goods or services to large corporations or government agencies, confirm whether they require MBS-validated invoices. Non-validated invoices may be rejected by their accounts payable systems.

## Penalties for Non-Compliance

FIRS enforces invoice requirements under the VAT Act and the FIRS Establishment Act:

### Financial Penalties
- **Failure to issue a tax invoice:** ₦50,000 for the first offence; ₦100,000 for each subsequent offence
- **Charging VAT without registration:** FIRS can recover all VAT collected plus a **150% surcharge**
- **Incorrect VAT calculation:** Assessment of the shortfall plus interest at the prevailing CBN rate

### Commercial Consequences
- Clients withhold payment until a compliant invoice is provided
- Your buyers lose input VAT credits, damaging the relationship
- Inconsistent invoice numbering is a common audit trigger — once FIRS opens an audit on an invoice irregularity, they typically review three to five years of records

## Quick Compliance Checklist

Use this before sending any invoice:

- [ ] Labelled "Invoice" or "Tax Invoice"
- [ ] Your registered business name and address
- [ ] Your TIN
- [ ] VAT registration number (if applicable)
- [ ] Unique sequential invoice number
- [ ] Invoice date
- [ ] Client name and address (with their TIN for B2B)
- [ ] Specific description of goods or services
- [ ] Quantity and unit price per line item
- [ ] Subtotal, VAT (7.5%), and total amount due
- [ ] Your bank details or payment gateway link

## Frequently Asked Questions

**Do freelancers need a TIN on invoices?**
Yes. Any individual or business issuing formal invoices for commercial transactions in Nigeria should include their TIN. Individual TINs are obtained free of charge from FIRS.

**What is the VAT threshold?**
Businesses with annual turnover of ₦25 million or more must register for VAT. Below this threshold, VAT registration is optional.

**Can I invoice in USD?**
Yes, but VAT must be calculated in Naira using the prevailing CBN exchange rate at the time of supply.

---

*Create FIRS-compliant invoices in under two minutes — with TIN fields, automatic 7.5% VAT, and sequential numbering built in. Try the free [invoice generator for Nigerian businesses](/invoice-generator-nigeria).*`,
    },

    // =========================================================================
    // POST 2 — How to Send an Invoice via WhatsApp in Nigeria
    // Target keyword: "how to send invoice via WhatsApp Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'Send Invoices via WhatsApp in Nigeria',
        slug: 'how-to-send-invoice-via-whatsapp-nigeria',
        excerpt: 'A step-by-step guide to sending professional invoices via WhatsApp in Nigeria. Practical tips for freelancers and small businesses to get paid faster.',
        coverImage: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `If you run a business in Nigeria, WhatsApp is already your de facto office communication tool. Your clients are on it, your suppliers are on it, and your team is on it. So why would you email an invoice and then follow up with a WhatsApp message saying "please check your email"?

Sending invoices directly via WhatsApp is faster, more likely to be seen, and fits naturally into how Nigerian business works. This guide walks you through exactly how to do it professionally — from creating the invoice to following up on payment.

## Why WhatsApp Works for Invoicing in Nigeria

- **Near-100% open rate:** WhatsApp messages are read within minutes, not days
- **Works on any data plan:** A client in Owerri or Maiduguri can open a PDF attachment on a basic data plan
- **Voice-note follow-up:** You can follow up an overdue invoice with a voice note in the same thread — keeping the relationship warm while staying firm
- **Payment confirmation in the same thread:** Clients send their transfer receipts or Paystack confirmation screenshots right back in the chat
- **Searchable history:** Both you and your client can search the chat by amount, invoice number, or date

## What You Need Before You Start

1. **A professional invoice as a PDF** — not a screenshot, not a photo of a handwritten receipt
2. **All FIRS-required fields on the invoice** — business name, TIN, sequential invoice number, VAT if applicable, bank details ([see the full compliance guide](/guide))
3. **Your client's WhatsApp number** saved as a business contact
4. **WhatsApp Business** installed on your phone — it adds a professional profile, away messages, and quick replies

## Step-by-Step: Sending an Invoice via WhatsApp

### Step 1: Create Your Invoice

Use [InvoiceGenerator.ng](/invoice-generator-nigeria) to build a professional, FIRS-compliant invoice in under two minutes:

1. Enter your business name, address, and TIN
2. Add your client's name and address
3. List your services or products with quantities and prices
4. Apply VAT at 7.5% if you are VAT-registered
5. Add your bank account details or Paystack payment link

### Step 2: Download as PDF

Click **Download PDF**. You will receive a clean, branded PDF — rename it to something identifiable before sending:

> \`Invoice_BrightSolutions_AcmeCorp_March2026.pdf\`

A clearly named file is easier for your client's accounts team to file and reduces the chances of it getting lost.

### Step 3: Open WhatsApp and Find Your Client

Open WhatsApp Web or the phone app. Navigate to your client's chat.

**Tip:** If your client is a company, find out which team member handles invoices (finance officer, accountant, or procurement) and send directly to them — not the general company number.

### Step 4: Attach the PDF and Send a Short Message

In the chat:
1. Tap the **paperclip** (attachment) icon
2. Select **Document**
3. Choose your invoice PDF
4. Write a short, clear message before sending

**Message template:**
> "Hi [Client Name], please find attached Invoice #INV-2026-042 for ₦185,000 covering [brief description] for March 2026. Payment is due by [date]. Please let me know if you have any questions. Thank you!"

State the amount and due date in the message itself — your client sees both before opening the PDF, which dramatically reduces delays.

### Step 5: Send Bank Details as a Separate Message

Follow up immediately with your payment details as a plain-text message:

> "Payment details:
> Bank: Access Bank
> Account Name: Bright Solutions Limited
> Account Number: 0123456789
>
> Or pay via Paystack: [your link]"

Sending bank details as text lets your client copy-paste the account number without switching between apps. This small step eliminates the single most common cause of delayed payments in Nigerian B2B transactions.

### Step 6: Ask for a Read Confirmation

> "Please confirm you have received this. Let me know if any adjustments are needed."

This creates a timestamped acknowledgement in the chat — useful if a payment dispute arises later.

---

## Real-World Use Cases

### Freelance Graphic Designer — Lagos to Port Harcourt

Tobi completes a branding project for a client based in Port Harcourt:
- Design fee: ₦250,000
- VAT (7.5%): ₦18,750
- **Total: ₦268,750**

He creates the invoice on InvoiceGenerator.ng, downloads the PDF, and sends it via WhatsApp:

> "Hi Emeka! The branding project is complete. Please find Invoice #INV-2026-017 attached — total ₦268,750 including VAT. Bank details below. Excited to see the new brand live!"

The client confirms receipt within 10 minutes. Payment arrives the same afternoon. Total time from invoice creation to payment confirmation: under three hours.

### Caterer with a Monthly Corporate Contract — Kano

Fatima supplies corporate lunches to a Kano company on a ₦480,000 monthly contract (₦16,000/day × 30 days). She sends the invoice on the 1st of each month via WhatsApp to the client's procurement officer.

The procurement officer keeps the chat thread as her invoice archive — scrolling back to retrieve previous months without calling Fatima. No email threads, no lost attachments.

---

## Following Up on Overdue Invoices

If payment has not come in by the due date, use this escalation sequence:

**Day 1 after due date:**
> "Hi [Client], just checking in on Invoice #INV-2026-042 (₦185,000) which was due on [date]. Please let me know if you need anything from my end."

**Day 5:**
> "Hi [Client], following up on the above invoice. Please advise on the payment timeline. Thank you."

**Day 10:**
> "Hi [Client], this is a formal reminder that Invoice #INV-2026-042 (₦185,000) is now 10 days overdue. As per our agreement, a late fee of 2% per week applies from [due date]. Please confirm when payment will be made."

WhatsApp gives you a time-stamped, read-receipt-confirmed paper trail — far stronger than a phone call if the matter ever needs to be escalated.

## Common Mistakes to Avoid

- **Sending a screenshot instead of a PDF** — screenshots look amateur and can be cropped or altered
- **No message with the attachment** — always add the amount and due date in the message text
- **Using a personal WhatsApp for business** — open a WhatsApp Business account to keep work separate and appear more professional
- **No follow-up reminder** — set a calendar event on the due date of every invoice you send

## Automate WhatsApp Invoice Delivery

[InvoiceGenerator.ng's WhatsApp integration](/send-invoice-via-whatsapp-nigeria) lets you send invoices directly from the platform to any WhatsApp number — no downloading, no switching apps. Create the invoice, enter your client's number, and tap send. Done.

---

*Start sending professional WhatsApp invoices in under two minutes. Try the free [Nigerian invoice generator](/invoice-generator-nigeria) — no sign-up required.*`,
    },

    // =========================================================================
    // POST 3 — Invoice vs Receipt in Nigeria
    // Target keyword: "invoice vs receipt difference Nigeria"  (~1,000 words)
    // =========================================================================
    {
        title: 'Invoice vs Receipt in Nigeria',
        slug: 'invoice-vs-receipt-difference-nigeria',
        excerpt: 'What is the difference between an invoice and a receipt in Nigeria? Learn the legal distinctions, when to use each, and what FIRS requires from businesses.',
        coverImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `"Send me an invoice." "Can I get a receipt?" "Is this an invoice or a receipt?"

These two words are used interchangeably in everyday Nigerian business conversation, but they are legally and functionally different documents. Confusing them costs businesses money, creates payment disputes, and causes problems during FIRS audits.

Here is the definitive guide to understanding each document, when to issue which, and what the Federal Inland Revenue Service (FIRS) requires.

## The Short Answer

| | **Invoice** | **Receipt** |
|---|---|---|
| **When issued** | Before payment | After payment |
| **Purpose** | Request for payment | Proof of payment received |
| **Triggers VAT claim** | Yes (tax invoice) | No |
| **FIRS mandatory for** | VAT-registered businesses | All businesses upon payment |

## What Is an Invoice?

An invoice is a **formal request for payment** sent by a seller to a buyer after goods have been delivered or services completed. It says: *"Here is what I provided, here is what you owe me, and here is when I expect to be paid."*

### Mandatory Fields (FIRS Requirements)

A FIRS-compliant invoice must include:

- The word "Invoice" or "Tax Invoice" at the top
- Your registered business name and address
- Your Tax Identification Number (TIN)
- Your VAT registration number (if VAT-registered)
- A unique sequential invoice number (e.g. INV-2026-031)
- Invoice date and payment due date
- Client name and address
- Itemised description of goods or services
- Subtotal, VAT at 7.5% (where applicable), and total amount due
- Your bank details or payment gateway link

For a full breakdown of every required field, see the [InvoiceGenerator.ng invoicing guide](/guide).

### An Invoice Is Not Proof of Payment

A critical point: an invoice is a demand, not a confirmation. Until the client pays, the invoice sits as an open "accounts receivable" entry in your books.

**Example:**
> Bright Solutions Limited issues Invoice #INV-2026-031 to TechCorp Nigeria:
> - Web development services (Q1 2026): ₦350,000
> - VAT (7.5%): ₦26,250
> - **Total Due: ₦376,250**, payable within 30 days

TechCorp has received the invoice. The ₦376,250 has not moved. Bright Solutions is waiting for payment.

## What Is a Receipt?

A receipt is **proof that payment has been received**. It is issued by the seller to the buyer after the money arrives. It says: *"I confirm your payment has been received and your account is settled."*

### What a Receipt Should Include

- Receipt number (sequential, separate from invoice numbers)
- Date payment was received
- Name of the payer
- Description of what was paid for
- Amount paid
- Payment method (bank transfer, cash, POS, Paystack)
- Reference to the original invoice number

**Example:**
> Bright Solutions Limited issues Official Receipt #RCT-2026-031 to TechCorp Nigeria:
> - Payment received: ₦376,250 on 14 April 2026
> - Via bank transfer — GTBank, Ref: 2604140089
> - Settling Invoice #INV-2026-031 (Web development, Q1 2026)
> - **Balance outstanding: ₦0**

## The FIRS Perspective

### Only Invoices Unlock VAT Input Credits

This is the most commercially important distinction. Under the Nigerian VAT Act, only a valid **tax invoice** — not a receipt — can be used by a buyer to reclaim input VAT.

If your client pays ₦376,250 and you issue them only a receipt:
- They **cannot** claim back the ₦26,250 VAT they paid
- Their effective cost is ₦26,250 higher than it should be
- You have failed a statutory obligation as a VAT-registered supplier

This is why corporate clients and government agencies insist on tax invoices before they process payment — not receipts.

### Receipts Are Also Required

FIRS requires VAT-registered businesses to issue an official receipt or acknowledgement for every transaction where payment is received. The receipt should reference the original invoice number. Failure to issue receipts is a separate compliance gap from failure to issue invoices.

## When to Use Each Document

### Issue an Invoice When:
- You have completed work and are requesting payment
- The buyer is a business that needs to record expenses and claim VAT
- You want to set a formal payment due date with penalty terms
- The buyer has not yet paid you

### Issue a Receipt When:
- You have received payment in full or in part
- A client asks for proof they have paid you
- You are acknowledging a deposit (note the outstanding balance)
- You are in retail and issuing confirmation of a cash or POS transaction

### Issue Both When:
In any formal B2B transaction, issue an invoice before payment and a receipt after. Link them by referencing the invoice number on the receipt. Both documents together form the complete transaction record.

## Common Confusions Resolved

### "The client paid before I sent the invoice"

This happens often in Nigeria — a client makes an advance payment before formal invoicing. In this case:
1. Issue the invoice dated on or before the payment date, marked **"Paid in Full"** or **"Advance Payment Received"**
2. Issue a receipt referencing that invoice

### "Can a bank debit alert serve as a receipt?"

No. A debit alert from the client's bank proves they sent money. It does not prove you received it, nor does it constitute an official receipt from your business. **You** must issue the receipt.

### "My client says they already paid — where is my receipt?"

If a client paid you and you have not issued a receipt, they are right to ask. Issue one immediately. Neglecting receipts creates the conditions for "I already paid you" disputes.

## Keeping Both for Compliance

The Companies and Allied Matters Act (CAMA) 2020 and FIRS guidelines recognise invoices and receipts as distinct legal instruments:

- An **invoice** establishes that payment was claimed on a specific date for specific goods or services
- A **receipt** establishes that payment was made on a specific date

Together they form a complete transaction record. Keep both for a minimum of **7 years** (FIRS requires 10 years for VAT records).

## Create Both in Minutes

[InvoiceGenerator.ng](/invoice-generator-nigeria) generates FIRS-compliant invoices with all mandatory fields — TIN, sequential numbering, 7.5% VAT calculation, and your bank details — in under two minutes. No sign-up required.

For more on Nigerian invoicing requirements, FIRS compliance, and VAT obligations, visit the [InvoiceGenerator.ng invoicing guide](/guide).

---

*Stop confusing invoices and receipts — and start getting paid faster. Create your first compliant invoice free at [InvoiceGenerator.ng](/invoice-generator-nigeria).*`,
    },
];

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    console.log('Seeding batch 1 blog posts (3 posts)...\n');

    let author = await prisma.user.findFirst({ where: { isAdmin: true } });
    if (!author) {
        console.log('No admin user found — checking for any user...');
        author = await prisma.user.findFirst();
    }
    if (!author) {
        console.error('❌  No users found. Please sign up in the app first.');
        process.exit(1);
    }

    if (author.name !== 'Olivia S') {
        author = await prisma.user.update({
            where: { id: author.id },
            data: { name: 'Olivia S' },
        });
    }

    console.log(`Author: ${author.name} (${author.email})\n`);

    for (const post of posts) {
        const result = await prisma.blogPost.upsert({
            where: { slug: post.slug },
            update: { ...post, authorId: author.id },
            create: { ...post, authorId: author.id },
        });
        console.log(`✅  ${result.title}`);
        console.log(`    /blog/${result.slug}\n`);
    }

    console.log('Done — 3 posts live.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
        await pool.end();
    });
