import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({
    connectionString,
    ssl: connectionString?.includes('supabase') ? { rejectUnauthorized: false } : undefined,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA (Article JSON-LD auto-generated by app/blog/[slug]/page.tsx)
//
// Post 1 — "Invoice Payment Terms in Nigeria"
//   Meta title : "Invoice Payment Terms in Nigeria | InvoiceGenerator.ng" (54 chars)
//   Meta desc  : "A complete guide to invoice payment terms for Nigerian businesses:
//                 Net 7, Net 14, and Net 30 — with examples showing how the right
//                 terms speed up payment." (153 chars)
//
// Post 2 — "How to Get Paid Faster in Nigeria"
//   Meta title : "How to Get Paid Faster in Nigeria | InvoiceGenerator.ng" (55 chars)
//   Meta desc  : "Practical strategies to cut late invoice payments in Nigeria.
//                 Learn how deposits, Paystack links, WhatsApp follow-ups, and
//                 clear terms speed up collection." (153 chars)
//
// Post 3 — "Nigeria FIRS E-Invoicing: MBS Guide"
//   Meta title : "Nigeria FIRS E-Invoicing: MBS Guide | InvoiceGenerator.ng" (57 chars)
//   Meta desc  : "What is the FIRS Merchant Buyer Solution (MBS) and how does Nigeria's
//                 e-invoicing mandate affect your business? A plain-English guide
//                 for Nigerian businesses." (158 chars)
// ─────────────────────────────────────────────────────────────────────────────

const posts = [

    // =========================================================================
    // POST 1 — Invoice Payment Terms in Nigeria
    // Target keyword: "invoice payment terms Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'Invoice Payment Terms in Nigeria',
        slug: 'invoice-payment-terms-nigeria',
        excerpt: 'A complete guide to invoice payment terms for Nigerian businesses: Net 7, Net 14, and Net 30 — with examples showing how the right terms speed up payment.',
        coverImage: 'https://images.unsplash.com/photo-1607863680198-23d4b2565df0?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Payment terms are the single most underused tool in a Nigerian business owner's invoicing kit. Most people write "payment due on receipt" or nothing at all — and then wonder why clients pay three months late.

The payment terms on your invoice set the legal clock for when money is owed. Used correctly, they accelerate your cash flow, create leverage for late payment enforcement, and signal to clients that you run a professional operation. Here is everything you need to know about choosing, writing, and enforcing payment terms in Nigeria.

## What Are Invoice Payment Terms?

Payment terms are the conditions under which a buyer must pay a seller. They specify:

- **When** payment is due (the due date)
- **How** payment should be made (bank transfer, Paystack, cash)
- **What happens** if payment is late (penalties, interest)
- **Any discounts** available for early payment

They appear on your invoice, usually in a "Payment Terms" or "Notes" section, and form part of the commercial agreement between you and your client.

## Standard Payment Terms Used in Nigeria

### Net 7

Payment is due within **7 days** of the invoice date.

**Best for:** Small, fast-turnaround jobs; trusted repeat clients; deliverables already handed over.

**Example:**
> Ngozi completes a logo design on 1 April 2026 and invoices the client ₦95,000 on the same day.
> Payment terms: Net 7 → due by **8 April 2026**.

Net 7 is aggressive but appropriate for quick projects where the client has already received the deliverable.

### Net 14

Payment is due within **14 days** of the invoice date.

**Best for:** Standard freelance and SME invoices; new clients you have not extended credit to; services completed in full.

**Example:**
> A Kano-based copywriter delivers a website content package on 3 April 2026 and issues Invoice #INV-2026-022 for ₦180,000.
> Payment terms: Net 14 → due by **17 April 2026**.

Net 14 is the recommended default for most Nigerian freelancers and small businesses. It is long enough to be practical for clients but short enough to keep your cash flow moving.

### Net 30

Payment is due within **30 days** of the invoice date.

**Best for:** Large corporate clients; government agencies; clients with formal accounts payable (AP) processes that require purchase orders.

**Example:**
> A Lagos marketing agency delivers a ₦2.4 million brand campaign to a multinational client.
> Payment terms: Net 30 → due by 30 days after invoice date.

Many large Nigerian companies and government MDAs have internal payment cycles of 30–45 days and will not pay faster regardless of your terms. For these clients, Net 30 is realistic. For everyone else, it hands your cash flow to your client.

### Due on Receipt

Payment is expected **immediately** upon receiving the invoice.

**Best for:** Cash-only retail businesses; advance payments; clients with a history of late payment.

Practically speaking, "due on receipt" is rarely enforced to the letter in Nigerian B2B settings, but it is useful as a baseline for clients you do not fully trust.

### 50/50 Split — Deposit and Balance

- **50% upfront** before work begins
- **50% on delivery** before final files are handed over

**Best for:** Projects above ₦150,000; new clients; long-duration projects.

**Example:**
> A Port Harcourt web developer quotes ₦600,000 for a full e-commerce site.
> Invoice #PI-2026-005 (Proforma): ₦600,000 total
> Deposit invoice: ₦300,000 — due before project start
> Balance invoice: ₦300,000 — due on site delivery

This structure removes the risk of delivering a complete project and then chasing payment. Never hand over final deliverables before the balance is paid.

## How to Write Payment Terms on Your Invoice

Place your payment terms in the notes section at the bottom of the invoice. Be specific — vague terms create room for dispute.

**Weak:**
> "Payment due soon."

**Strong:**
> "Payment due by 17 April 2026 (Net 14). Please transfer to the account details above. A late fee of 2% per month applies to balances outstanding after the due date. For queries, contact us at hello@yourbusiness.ng."

Include:
- The exact due date (not just "Net 14" — calculate and state the date explicitly)
- Preferred payment method
- Late fee clause
- Contact for billing queries

## Early Payment Discounts

You can incentivise faster payment by offering a small discount for early settlement. The standard format in Nigeria is:

> "2/10 Net 30" — 2% discount if paid within 10 days; full amount due by day 30.

**Example:**
> Invoice: ₦500,000 (Net 30 — due 1 May 2026)
> Early payment discount: Pay by 11 April 2026 and deduct ₦10,000 (2%)
> Early payment amount: ₦490,000

For cash-flow-sensitive periods, early payment discounts are often cheaper than a bank overdraft.

## Late Payment Penalties

Always include a late payment clause. The most common structure in Nigerian professional services:

> "A late fee of 2% of the outstanding invoice balance will be charged for every 30 days (or part thereof) that payment remains overdue after the due date."

**Calculation example:**
> Invoice: ₦350,000, due 17 April 2026
> Paid: 25 May 2026 (38 days late — two partial 30-day periods)
> Late fee: ₦350,000 × 4% = ₦14,000
> **Total payable: ₦364,000**

State the clause on every invoice. Whether you enforce it fully every time is a relationship decision, but having it in writing means you always have legitimate grounds to push for faster payment.

## Matching Terms to Your Business Type

| Business type | Recommended default | Notes |
|---|---|---|
| Freelancer (under ₦500k projects) | Net 14 | Take 50% deposit on new clients |
| Agency / studio | Net 14–21 | Milestone payments on large projects |
| Supplier / manufacturer | Net 30 | Confirm AP cycles with corporate buyers |
| Retail / service walk-in | Due on receipt | Cash or POS on the day |
| Government contracts | Net 30–45 | Build this into your pricing |

## Frequently Asked Questions

**What if my client insists on Net 60?**
Negotiate — politely but firmly. Offer Net 30 as a compromise. If they insist on 60 days, factor the cash flow delay into your pricing (a 2–3% premium is reasonable). Never simply accept terms that hurt your cash flow without compensation.

**Can I change payment terms on existing clients?**
Yes, but communicate the change in writing before issuing the next invoice. Give at least 30 days' notice: *"From 1 June 2026, our standard payment terms will move from Net 30 to Net 14. Please update your records accordingly."*

**Do payment terms hold up legally in Nigeria?**
Yes. Payment terms stated on an invoice — and implicitly accepted when the client receives and does not dispute the invoice — form part of your commercial agreement. They are enforceable in Nigerian courts under the general law of contract.

---

*Set the right payment terms and start getting paid on time. Create professional invoices with built-in payment terms at [InvoiceGenerator.ng](/invoice-generator-nigeria) — or read the full [Nigerian invoicing guide](/guide).*`,
    },

    // =========================================================================
    // POST 2 — How to Get Paid Faster in Nigeria
    // Target keyword: "how to get paid faster Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'How to Get Paid Faster in Nigeria',
        slug: 'how-to-get-paid-faster-nigeria',
        excerpt: 'Practical strategies to cut late invoice payments in Nigeria. Learn how deposits, Paystack links, WhatsApp follow-ups, and clear terms speed up collection.',
        coverImage: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Late payments are one of the biggest cash flow killers for Nigerian freelancers and small businesses. A survey of Nigerian SME owners consistently shows that 60–70% of outstanding invoices are paid late — and a significant portion are never paid at all.

The good news: most late payments are preventable. The difference between a business that gets paid on time and one that constantly chases invoices is rarely the client — it is the invoicing system. Here are eight proven strategies to cut your payment delays starting today.

## Why Nigerian Businesses Struggle with Late Payments

Before fixing the problem, understand the cause. Late payments in Nigeria typically come from:

- **No clear due date** — "pay when you can" is not a due date
- **Inconvenient payment methods** — clients who have to visit a bank are slower than clients who click a link
- **No follow-up system** — invoices sent into a void with no reminder
- **No consequences** — clients who know there is no late fee have no incentive to prioritise you
- **Invoices lost in email** — a PDF attachment in an inbox competes with hundreds of other emails

Each of these is fixable.

## 1. Always Take a Deposit Before Starting Work

The most powerful thing you can do to protect your cash flow is to collect money before delivering anything.

**Standard deposit structure:**
- Projects under ₦100,000: 50% upfront, 50% on delivery
- Projects ₦100,000–₦500,000: 50% upfront, 50% on delivery
- Projects above ₦500,000: 40% upfront, 30% at milestone, 30% on final delivery

**Why it works:** A client who has already paid half is financially committed. They have skin in the game. They are also far more likely to review your work promptly because their money is already spent.

**Script for new clients:**
> "My standard process is to require a 50% deposit before work begins. This secures your project slot in my schedule. I'll send you a deposit invoice now — once that's settled, we'll kick off immediately."

If a client refuses to pay any deposit, that is usually a sign about future payment behaviour. Factor it into your decision to take the project.

## 2. Shorten Your Default Payment Terms

If you currently use Net 30, switch to Net 14. If you use Net 14, try Net 7 for smaller projects.

**The research is clear:** the longer your payment window, the later the average actual payment. Net 30 clients pay in 45–60 days. Net 14 clients pay in 18–25 days. Shorter terms set a tighter psychological anchor.

For corporate clients with fixed AP cycles who genuinely cannot pay in 14 days, offer an early payment discount:
> "Net 30 standard — or 2% discount if settled within 10 days."

A 2% discount on ₦500,000 costs you ₦10,000 but saves you 20 days of cash flow. That is often worth it.

## 3. Add a Paystack Payment Link to Every Invoice

This is the single highest-impact change most Nigerian businesses can make. When a client has to:
1. Log in to internet banking
2. Add a beneficiary
3. Enter your account number
4. Wait for OTP
5. Confirm the transfer

…some of them put it off. When a client can:
1. Click a link
2. Enter card details
3. Pay in 30 seconds

…the payment happens immediately.

[InvoiceGenerator.ng](/invoice-generator-nigeria) lets you add a Paystack payment link directly to your invoice. Your client clicks, pays, and you receive an alert — no follow-up needed.

**Example invoice note:**
> "Pay instantly via card: [Paystack link] — or transfer to Access Bank, Bright Solutions Ltd, 0123456789."

Give clients the easy option and most of them will take it.

## 4. Send Invoices via WhatsApp, Not Just Email

Email open rates in Nigerian B2B hover around 20–30%. WhatsApp messages are read by over 95% of recipients, usually within minutes.

**WhatsApp invoice delivery workflow:**
1. Create invoice on InvoiceGenerator.ng
2. Download as PDF
3. Open the client's WhatsApp chat
4. Attach the PDF and write: *"Hi [Name], please find Invoice #INV-2026-031 attached — ₦245,000 due by [date]. Bank details below. Let me know if you have any questions."*
5. Send your bank details as a separate text message in the same chat

The client sees the amount and due date before they even open the PDF. That alone reduces "I didn't see it" excuses significantly.

For a full guide on this process, see our post on [sending invoices via WhatsApp in Nigeria](/blog/how-to-send-invoice-via-whatsapp-nigeria).

## 5. Follow Up Before the Due Date

Most businesses only follow up after payment is late. The most effective approach is to follow up *before* — a brief, friendly reminder 3 days before the due date.

**Pre-due reminder (3 days before):**
> "Hi [Client], just a quick heads-up — Invoice #INV-2026-031 (₦245,000) is due on [date]. Please let me know if you need anything."

This does three things:
- Keeps the invoice top of mind
- Creates an acknowledgement thread
- Surfaces any problems (missing bank details, wrong amount) before they become a delay

Set a calendar reminder for every invoice you send: one 3 days before, one on the due date.

## 6. State Late Payment Penalties Clearly and Enforce Them

Adding "2% late fee per month" to your invoice is only effective if you actually charge it — at least occasionally.

**Escalation sequence:**
- **Day 1 overdue:** Polite reminder, reference the invoice number and amount
- **Day 5:** Follow-up, flag that the account is overdue
- **Day 10:** Formal notice referencing the late fee clause, state the new total
- **Day 14+:** Issue an updated invoice showing the original amount plus accrued late fee

**Day 10 message example:**
> "Hi [Client], Invoice #INV-2026-031 (₦245,000) is now 10 days overdue. As per our agreed terms, a late fee of 2% per month applies from [due date]. The updated amount due is ₦249,900. Please confirm payment date."

The client who knows there are real financial consequences is faster than the one who believes there are none.

## 7. Issue Invoices Immediately on Completion

Every day between completing work and sending the invoice is a day added to your payment wait. The client's enthusiasm is highest immediately after delivery — that is when they are most motivated to pay.

Send the invoice the same day you complete the work. Ideally, send a proforma invoice before you even begin, so the client knows exactly what the bill will look like.

## 8. Use Professional Invoices That Look Hard to Ignore

A handwritten receipt, a WhatsApp voice note with bank details, or a Word document with no invoice number sends a signal: this person is informal, they probably will not chase me up.

A clean, professionally formatted invoice with a sequential number, your TIN, a specific due date, and a late fee clause sends the opposite signal.

[InvoiceGenerator.ng](/invoice-generator-nigeria) generates invoices that look polished and professional — the kind that go to the top of the payment queue. Try the free [Nigerian invoicing guide](/guide) for more strategies on running a tight invoicing process.

## Summary: Your Fast-Payment Checklist

- [ ] Deposit collected before work starts
- [ ] Payment terms shortened to Net 14 or less
- [ ] Paystack link included on the invoice
- [ ] Invoice sent via WhatsApp, not only email
- [ ] Pre-due reminder scheduled for 3 days before due date
- [ ] Late fee clause stated clearly on every invoice
- [ ] Invoice sent on the day work is completed
- [ ] Professional invoice format used consistently

---

*Stop chasing payments. Start getting paid on time — create your next invoice free at [InvoiceGenerator.ng](/invoice-generator-nigeria).*`,
    },

    // =========================================================================
    // POST 3 — Nigeria FIRS E-Invoicing: MBS Guide
    // Target keyword: "FIRS e-invoicing Nigeria MBS"  (~1,000 words)
    // =========================================================================
    {
        title: 'Nigeria FIRS E-Invoicing: MBS Guide',
        slug: 'firs-e-invoicing-nigeria-mbs-guide',
        excerpt: 'What is the FIRS Merchant Buyer Solution (MBS) and how does Nigeria\'s e-invoicing mandate affect your business? A plain-English guide for Nigerian businesses.',
        coverImage: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `Nigeria is in the middle of one of the most significant changes to business invoicing in its history. The Federal Inland Revenue Service (FIRS) is rolling out a mandatory electronic invoicing system — the **Merchant Buyer Solution (MBS)** — that will eventually require all VAT-registered businesses to issue digitally validated invoices for every taxable transaction.

If you run a business in Nigeria and issue invoices, this affects you. Here is everything you need to know in plain English.

## What Is the FIRS Merchant Buyer Solution (MBS)?

The Merchant Buyer Solution is Nigeria's national e-invoicing framework, developed by FIRS to digitise the issuance, validation, and reporting of invoices across the Nigerian economy.

Under MBS:

- Every B2B invoice above a specified threshold must be **validated by FIRS** before it is considered legally compliant
- Validated invoices receive a unique **Invoice Reference Number (IRN)** and a **QR code**
- The QR code allows buyers — and FIRS auditors — to verify the invoice's authenticity instantly by scanning it
- Transaction data flows in near real-time from businesses to FIRS, reducing VAT fraud and the tax gap

Think of it as giving every invoice a government-issued serial number and a digital signature. An invoice without IRN and QR code will not qualify as a valid tax invoice for VAT input credit purposes.

## Why Is FIRS Introducing E-Invoicing?

Nigeria's VAT compliance rate has historically been low relative to the size of the economy. FIRS estimates that a significant portion of VAT collected never reaches government coffers — partly through fraud, partly through informal invoicing practices.

The MBS solves this by creating a real-time audit trail for every transaction. Key objectives:

- **Eliminate ghost invoices** — fake invoices used to claim fraudulent VAT refunds
- **Close the VAT gap** — capture transactions currently conducted off the books
- **Simplify audits** — FIRS can verify any invoice by scanning its QR code rather than requesting paper records
- **Enable faster VAT refunds** — with verified transaction data, legitimate refund claims can be processed more quickly

## How Does MBS Work?

The MBS operates through a network of **Accredited Access Point Providers (AAPPs)** — certified technology providers that connect businesses to the FIRS validation system. The workflow is:

1. **You create an invoice** in your accounting software or invoicing platform
2. **Your software submits the invoice data** to an AAPP via API
3. **The AAPP forwards the data** to the FIRS MBS portal for validation
4. **FIRS returns a unique IRN** (Invoice Reference Number) and approves the invoice
5. **The IRN and QR code are added** to your invoice automatically
6. **You issue the validated invoice** to your buyer

For B2C transactions (businesses selling to consumers), the process is simpler — a till receipt or POS-generated document with a fiscal device code may suffice.

## Who Is Affected?

### Currently Required (Phase 1)

Large taxpayers — businesses identified by FIRS as high-volume VAT payers — were the first group brought under mandatory MBS compliance. If FIRS has contacted your business directly about MBS enrolment, you are in this category.

### Next Phase

Medium-sized taxpayers (typically businesses with annual turnover above ₦150–250 million, though FIRS has not published a definitive threshold) will be brought on in subsequent rollout phases.

### Small Businesses and Freelancers

Businesses with turnover below the VAT registration threshold of ₦25 million are not currently required to participate in MBS. However, many are preparing voluntarily — particularly those who supply goods or services to large corporations that will require MBS-validated invoices from their vendors.

## What Does a Valid MBS E-Invoice Include?

In addition to the standard FIRS invoice fields (covered in detail in our [Nigerian invoicing guide](/guide)), an MBS-validated invoice includes:

- **Invoice Reference Number (IRN)** — a unique alphanumeric string issued by FIRS
- **QR code** — encodes the IRN and key invoice data; scannable by any QR reader
- **Digital timestamp** — records when validation occurred
- **AAPP identifier** — shows which Access Point Provider processed the invoice

All other mandatory fields remain: business name, TIN, VAT registration number, sequential invoice number, client TIN (for B2B), itemised description, VAT at 7.5%, and payment details.

## Key Dates and Rollout Timeline

FIRS has been phasing in MBS since 2023 without a single hard compliance deadline for all businesses. The current status:

| Phase | Businesses | Status |
|---|---|---|
| Phase 1 | Large taxpayers (FIRS-identified) | Active — mandatory |
| Phase 2 | Medium taxpayers | Rolling out — check with FIRS |
| Phase 3 | Small taxpayers and SMEs | Planned — timeline unconfirmed |

**Important:** FIRS has indicated that at full implementation, any VAT-registered business issuing invoices without MBS validation may face penalties — including the inability of buyers to claim input VAT on those invoices.

Monitor the FIRS website (firs.gov.ng) and your FIRS correspondence for notifications about when your business will be required to enrol.

## What Should Nigerian Businesses Do Now?

### 1. Confirm Your Current Obligation

If you have received direct correspondence from FIRS about MBS enrolment, act immediately. If not, and your turnover is below ₦150 million, you likely have time — but should prepare.

### 2. Identify an Accredited Access Point Provider

FIRS publishes a list of AAPPs on its website. Compare providers by:
- Integration method (API, web portal, or software plugin)
- Cost per invoice or monthly subscription
- Compatibility with your existing invoicing software

### 3. Get Your Invoicing Software MBS-Ready

Your invoicing platform must be able to:
- Submit invoice data to an AAPP via API
- Receive and display the IRN and QR code on the final invoice
- Archive validated invoices with their IRNs for audit purposes

### 4. Ensure Your Basic Invoices Are Already Compliant

Regardless of MBS status, your invoices must already include all mandatory FIRS fields. If they do not, fix that first — it is the foundation that MBS builds on. Use [InvoiceGenerator.ng](/invoice-generator-nigeria) to create fully compliant invoices with all required fields.

### 5. Train Your Finance Team

Your accounts staff need to understand:
- Why the IRN and QR code must appear on every invoice before it is sent
- How to handle a validation failure (e.g., network timeout during submission)
- How to verify incoming invoices from suppliers using the QR code

## Frequently Asked Questions

**If I am not VAT-registered, do I need MBS?**
No. MBS applies to VAT-registered businesses. If your turnover is below ₦25 million, you are not required to register for VAT and therefore not subject to MBS.

**Can buyers still claim input VAT on non-MBS invoices?**
In the current transition period, FIRS has not formally blocked input VAT claims on non-MBS invoices from businesses not yet enrolled in the system. However, as enforcement tightens, invoices without IRN and QR codes may be rejected. Check with your tax adviser.

**What happens if the FIRS portal is down when I need to issue an invoice?**
AAPPs are required to maintain fallback mechanisms. Your AAPP should provide guidance on how to issue invoices during outages — typically a temporary offline mode with deferred validation.

---

*Stay ahead of FIRS compliance. Create professional, FIRS-ready invoices with all mandatory fields at [InvoiceGenerator.ng](/invoice-generator-nigeria). Read the full compliance guide at [InvoiceGenerator.ng/guide](/guide).*`,
    },
];

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    console.log('Seeding batch 3 blog posts (3 posts)...\n');

    let author = await prisma.user.findFirst({ where: { isAdmin: true } });
    if (!author) {
        console.log('No admin user found — checking for any user...');
        author = await prisma.user.findFirst();
    }
    if (!author) {
        console.error('❌  No users found. Please sign up in the app first.');
        process.exit(1);
    }

    if (author.name !== 'Olivia S') {
        author = await prisma.user.update({
            where: { id: author.id },
            data: { name: 'Olivia S' },
        });
    }

    console.log(`Author: ${author.name} (${author.email})\n`);

    for (const post of posts) {
        const result = await prisma.blogPost.upsert({
            where: { slug: post.slug },
            update: { ...post, authorId: author.id },
            create: { ...post, authorId: author.id },
        });
        console.log(`✅  ${result.title}`);
        console.log(`    /blog/${result.slug}\n`);
    }

    console.log('Done — 3 posts live.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
        await pool.end();
    });
