import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({
    connectionString,
    ssl: connectionString?.includes('supabase') ? { rejectUnauthorized: false } : undefined,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────────────────────────────────────
// SEO METADATA (Article JSON-LD auto-generated by app/blog/[slug]/page.tsx)
//
// Post 1 — "VAT Invoice Format Nigeria"
//   Meta title : "VAT Invoice Format Nigeria | InvoiceGenerator.ng" (48 chars)
//   Meta desc  : "Learn how to correctly format a VAT invoice in Nigeria. FIRS-required
//                 fields, 7.5% VAT calculation, and practical Naira examples for
//                 every type of business." (156 chars)
//
// Post 2 — "Freelancer Invoicing Guide Nigeria"
//   Meta title : "Freelancer Invoicing Guide Nigeria | InvoiceGenerator.ng" (56 chars)
//   Meta desc  : "A complete invoicing guide for Nigerian freelancers: professional
//                 invoice setup, payment terms, late payment penalties, and
//                 strategies to get paid faster." (153 chars)
//
// Post 3 — "Proforma Invoice Nigeria: What It Is"
//   Meta title : "Proforma Invoice Nigeria: What It Is | InvoiceGenerator.ng" (58 chars)
//   Meta desc  : "What is a proforma invoice in Nigeria and when should you use one?
//                 Learn the difference from a tax invoice and how to create one
//                 correctly for clients." (150 chars)
// ─────────────────────────────────────────────────────────────────────────────

const posts = [

    // =========================================================================
    // POST 1 — VAT Invoice Format Nigeria
    // Target keyword: "VAT invoice format Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'VAT Invoice Format Nigeria',
        slug: 'vat-invoice-format-nigeria',
        excerpt: 'Learn how to correctly format a VAT invoice in Nigeria. FIRS-required fields, 7.5% VAT calculation, and practical Naira examples for every type of business.',
        coverImage: 'https://images.unsplash.com/photo-1568234928966-359c35dd8327?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `A VAT invoice is not just any invoice with a tax line added at the bottom. Under Nigerian law, it is a specific legal document that must meet the exact format prescribed by the Federal Inland Revenue Service (FIRS). If any mandatory field is missing or incorrect, your buyer cannot claim input VAT — and you face potential penalties.

This guide explains the correct VAT invoice format for Nigeria, field by field, with practical ₦ examples for common business types. For the full picture on Nigerian invoicing requirements, see the [InvoiceGenerator.ng guide](/guide).

## Who Must Issue VAT Invoices?

Any business with an annual taxable turnover of **₦25 million or more** is required to register for VAT and issue a tax invoice (also called a VAT invoice) for every taxable supply. Businesses below the ₦25 million threshold are not required to charge VAT, but many register voluntarily — particularly when their clients are large corporates or government agencies that need VAT invoices to claim input tax.

Key rule: if you charge VAT on an invoice without being VAT-registered, FIRS can demand repayment of all VAT collected plus a 150% penalty. Only issue VAT invoices if you are registered.

## The Correct VAT Invoice Format: All Required Fields

### Field 1 — Document Title: "Tax Invoice"

Write **Tax Invoice** prominently at the top of the document. This label distinguishes it from a proforma invoice, a quotation, a delivery note, or a standard invoice not subject to VAT.

### Field 2 — Your Business Details

Include all of the following:
- **Registered business name** (exactly as registered with CAC)
- **Registered address** — full street address, not a P.O. Box
- **Phone number and email address**
- **RC or BN number** (Corporate Affairs Commission registration number)

**Example:**
> Prime Digital Services Limited
> 7B Admiralty Way, Lekki Phase 1, Lagos
> Tel: 0802 345 6789 | hello@primedigital.ng
> RC: 1456789

### Field 3 — Tax Identification Number (TIN)

Your TIN is mandatory on every tax invoice. It is an 8-digit number issued by FIRS (e.g., \`12345678-0001\`). Without it, your invoice is not FIRS-compliant, regardless of how correct everything else is.

### Field 4 — VAT Registration Number

Your VAT registration number is separate from your TIN and is issued when you register for VAT. It must appear on every tax invoice. Format: typically begins with the letters "VRN" followed by digits (e.g., VRN-12345678-0001).

### Field 5 — Unique Invoice Number

Each invoice must carry a **unique, sequential invoice number** that does not repeat within a calendar year. FIRS requires an unbroken sequence.

**Recommended format:**
> INV-2026-001, INV-2026-002, INV-2026-003...

Never skip or reuse numbers. A gap in your invoice sequence is a red flag during audits.

### Field 6 — Invoice Date

The date on which the invoice is issued. For VAT invoices, Nigerian law requires that you issue the invoice **within 15 days of the end of the month** in which the supply took place.

**Example:** Service delivered on 22 March 2026 → invoice must be issued by 15 April 2026.

### Field 7 — Your Client's Details

Include:
- Full name or registered company name
- Address
- TIN (strongly recommended for B2B — required for the buyer to claim input VAT)

### Field 8 — Description of Supply

Describe each item or service clearly and specifically. Vague entries like "Services Rendered" are inadequate for VAT purposes.

| Description | Qty | Unit Price |
|---|---|---|
| Social media management — March 2026 | 1 month | ₦120,000 |
| Paid ad campaign setup and management | 1 | ₦80,000 |
| Monthly performance report | 1 | ₦25,000 |

### Field 9 — Subtotal, VAT, and Total

This is the section most businesses get wrong. VAT must be shown as a **separate line item**, not embedded in the total.

**Correct format:**
> Subtotal: ₦225,000
> VAT (7.5%): ₦16,875
> **Total Due: ₦241,875**

**Incorrect format:**
> Total (including VAT): ₦241,875 ✗

The buyer needs to see the VAT amount explicitly to claim it as input credit.

### Field 10 — Payment Due Date and Terms

State clearly when payment is due and any penalty for late payment:
> Payment due: 30 April 2026 (Net 30)
> Late fee: 2% per month on overdue balances

### Field 11 — Payment Details

Provide:
- Bank name
- Account name (must match your registered business name)
- NUBAN account number
- Paystack or Flutterwave payment link (if applicable)

---

## A Complete VAT Invoice Example

Here is a full VAT invoice for a Nigerian marketing agency:

---

**TAX INVOICE**

**Prime Digital Services Limited**
7B Admiralty Way, Lekki Phase 1, Lagos | RC: 1456789
TIN: 12345678-0001 | VRN: VRN-12345678-0001

**Invoice #:** INV-2026-028
**Invoice Date:** 2 April 2026
**Due Date:** 2 May 2026 (Net 30)

**Bill To:**
TechCorp Nigeria Limited
Plot 44, Central Business District, Abuja
TIN: 98765432-0001

| Item | Qty | Unit Price | Total |
|---|---|---|---|
| Social media management (March 2026) | 1 | ₦120,000 | ₦120,000 |
| Paid ad campaign management | 1 | ₦80,000 | ₦80,000 |
| Monthly analytics report | 1 | ₦25,000 | ₦25,000 |
| **Subtotal** | | | **₦225,000** |
| **VAT (7.5%)** | | | **₦16,875** |
| **Total Due** | | | **₦241,875** |

**Payment:**
Bank: Zenith Bank | Account Name: Prime Digital Services Limited | Account: 2012345678

*Payment due 2 May 2026. A late fee of 2% per month applies after the due date.*

---

## VAT on Exempt and Zero-Rated Items

Not every supply attracts VAT at 7.5%. The following categories are **VAT-exempt** under Schedule 1 of the VAT Act:

- Basic food items (unprocessed agricultural products)
- Medical and pharmaceutical products
- Educational materials (books, newspapers)
- Baby products
- Exported services and goods

If your invoice contains a mix of taxable and exempt items, calculate VAT only on the taxable portion and clearly label which lines are exempt.

**Example — catering business:**
> Jollof rice and proteins (exempt food supply): ₦50,000 — VAT: ₦0
> Event venue arrangement and décor (taxable service): ₦150,000 — VAT: ₦11,250
> **Total VAT: ₦11,250**

## Common VAT Invoice Mistakes

- **Not separating VAT from the subtotal** — VAT must be a distinct line item
- **Using a TIN instead of a VAT registration number** — these are different numbers
- **Charging VAT without registration** — this attracts a 150% penalty
- **Rounding VAT incorrectly** — always calculate 7.5% precisely; do not round up for convenience
- **Issuing the invoice late** — beyond 15 days after month-end is a compliance breach

## Create Correctly Formatted VAT Invoices Instantly

[InvoiceGenerator.ng](/invoice-generator-nigeria) automatically applies the correct VAT invoice format — with dedicated TIN and VAT registration number fields, a separate VAT calculation line, and sequential numbering. Every invoice you generate meets FIRS requirements from the first field to the last.

---

*Stop worrying about VAT invoice formatting. Try the free [Nigerian invoice generator](/invoice-generator-nigeria) — correct format, every time.*`,
    },

    // =========================================================================
    // POST 2 — Invoice Generator for Freelancers Nigeria
    // Target keyword: "invoice generator for freelancers Nigeria"  (~1,200 words)
    // =========================================================================
    {
        title: 'Freelancer Invoicing Guide Nigeria',
        slug: 'invoice-generator-freelancers-nigeria',
        excerpt: 'A complete invoicing guide for Nigerian freelancers: professional invoice setup, payment terms, late payment penalties, and strategies to get paid faster.',
        coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `If you freelance in Nigeria — as a designer, developer, writer, photographer, consultant, or any other creative or technical professional — invoicing is one of the most important business skills you can develop. A weak invoice gets ignored. A professional one gets paid.

This guide covers everything a Nigerian freelancer needs to know: how to set up your invoice, what terms to use, how to handle late payments, and how to protect yourself when clients push back.

## Why Invoicing Properly Matters for Nigerian Freelancers

Many freelancers treat invoices as an afterthought — a PDF sent after the work is done, with a bank account number and a prayer. But your invoice does much more than request payment:

- It sets the legal terms of your transaction
- It creates a paper trail for FIRS if your income is ever audited
- It gives you leverage in payment disputes
- It signals to clients that you are a professional, not a favour

Clients — especially agencies and corporate clients — are far more likely to prioritise payment to freelancers who send clean, professional invoices with clear due dates and consequences for late payment.

## Setting Up Your Invoicing Details

Before you send your first invoice, get these in order:

### Tax Identification Number (TIN)

As a Nigerian freelancer earning income from commercial activities, you are expected to include your TIN on formal invoices. Individual TINs are free and can be obtained through the FIRS portal or any FIRS office with your National ID Number (NIN) or BVN.

Once you earn ₦25 million or more in a calendar year, VAT registration becomes mandatory. Until then, you do not charge VAT — and you must not add a "VAT" line to your invoice.

### Your Bank Account

Use a dedicated **business account** for your freelance income. A personal account mixed with business receipts is a bookkeeping headache and raises questions if FIRS ever reviews your finances. Most Nigerian banks offer free or low-cost business accounts for sole traders.

### Your Invoice Numbering System

Start with INV-2026-001 and increment from there. Never skip or reuse numbers. If you work across multiple clients, a sequential global series (not one per client) is simpler and FIRS-compliant.

## What to Include on Every Freelance Invoice

A FIRS-compliant freelance invoice must contain:

- Your name (or business trading name) and address
- Your TIN
- Your unique sequential invoice number
- Invoice date and payment due date
- Client name and address
- Itemised description of services rendered
- Quantity or units (hours, days, deliverables)
- Unit rate and line total
- Subtotal and total due
- Your bank name, account name, and NUBAN number

For a full checklist, see the [invoicing guide](/guide).

**Example — freelance web developer in Abuja:**

> **Invoice #INV-2026-014**
> Tunde Okafor | Web Developer | Wuse 2, Abuja | TIN: 23456789-0001
>
> Bill To: Greenfield Startups Ltd, Plot 6, Jabi, Abuja
>
> | Service | Hours | Rate/hr | Total |
> |---|---|---|---|
> | Frontend development (React) | 40 | ₦8,500 | ₦340,000 |
> | UI/UX review and revisions | 8 | ₦8,500 | ₦68,000 |
> | Project management & calls | 6 | ₦5,000 | ₦30,000 |
> | **Total Due** | | | **₦438,000** |
>
> Payment due: 16 April 2026 (Net 14)
> Bank: First Bank | Tunde Okafor | 3012345678

## Setting Payment Terms That Protect You

Payment terms are one of the most underused tools in a Nigerian freelancer's arsenal.

### Choose the Right Net Term

| Term | Due date | Best for |
|---|---|---|
| **Net 7** | 7 days from invoice | Small, fast projects; trusted repeat clients |
| **Net 14** | 14 days from invoice | Standard for most freelance work |
| **Net 30** | 30 days from invoice | Corporate clients with formal AP processes |
| **Due on receipt** | Immediately | Retainer payments, deposits |

Default to **Net 14** for new clients. Net 30 is a courtesy you extend after you have established trust — not a starting position.

### Always Take a Deposit

For projects above ₦100,000, request a **50% upfront deposit** before starting work. This is standard professional practice in Nigeria and internationally. Include it on the invoice:

> Deposit due (50% — payable before work commences): ₦219,000
> Balance due on delivery: ₦219,000

A deposit weeds out clients who are not serious and reduces your financial exposure if a project falls apart mid-way.

### Require Milestone Payments for Large Projects

For projects above ₦500,000, break payment into milestones tied to deliverables:

- 40% on project kickoff
- 30% on first deliverable approved
- 30% on final delivery

Never deliver the final files or completed work before the final payment is received.

## Late Payment Penalties: How to Word Them

The most effective late payment clause in a Nigerian freelance invoice:

> *"Payment is due by [date]. A late fee of 2% of the outstanding balance will be applied for every 30 days (or part thereof) that payment remains overdue."*

Add this to the notes section of every invoice. When a client is late, you reference this clause — it is already a term they implicitly agreed to by accepting your services.

**Example calculation:**
- Invoice amount: ₦438,000
- Due date: 16 April 2026
- Actual payment date: 25 May 2026 (39 days late — 2 partial 30-day periods)
- Late fee: ₦438,000 × 4% = **₦17,520**
- **Total payable: ₦455,520**

Whether you enforce the full late fee every time is a relationship judgement call — but having it in writing gives you legitimate leverage to push for faster payment.

## Following Up Without Ruining the Relationship

Most Nigerian freelancers hate chasing invoices. Here is a sequence that is firm without being aggressive:

**3 days before due date:**
> "Hi [client], just a friendly heads-up that Invoice #INV-2026-014 (₦438,000) is due on [date]. Please let me know if you need anything from my end."

**On the due date:**
> "Hi [client], Invoice #INV-2026-014 is due today. Please confirm once the transfer is done."

**3 days after due date:**
> "Hi [client], your invoice is now 3 days overdue. Please advise on the payment date. Note that a 2% late fee applies per our agreed terms."

**2 weeks overdue:**
> "Hi [client], Invoice #INV-2026-014 (₦438,000 + ₦8,760 late fee) is now 14 days past due. I need a confirmed payment date by [date], failing which I will have to pause any current or future work until this is resolved."

## Tools That Make Freelance Invoicing Easy

Manual invoice creation in Word or Excel works — until it does not. A dedicated tool removes calculation errors, maintains sequential numbering, and saves your client details for future invoices.

[InvoiceGenerator.ng](/invoice-generator-nigeria) is built for Nigerian freelancers:
- Pre-configured for Naira (₦)
- TIN field built in
- Automatic sequential invoice numbering
- Late fee and payment terms fields
- Download as PDF or send via WhatsApp in one click
- No sign-up required for basic use

For a complete breakdown of what every Nigerian invoice must include, read the [full invoicing guide](/guide).

---

*Create your first professional freelance invoice in under two minutes — free, no sign-up. Try [InvoiceGenerator.ng](/invoice-generator-nigeria).*`,
    },

    // =========================================================================
    // POST 3 — Proforma Invoice Nigeria
    // Target keyword: "proforma invoice Nigeria"  (~1,000 words)
    // =========================================================================
    {
        title: 'Proforma Invoice Nigeria: What It Is',
        slug: 'proforma-invoice-nigeria-what-it-is',
        excerpt: 'What is a proforma invoice in Nigeria and when should you use one? Learn the difference from a tax invoice and how to create one correctly for clients.',
        coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=2000',
        published: true,
        content: `A proforma invoice is one of the most misunderstood documents in Nigerian business. Some business owners treat it like a proper invoice; others confuse it with a quotation. Get it wrong and you may send the wrong document at the wrong time — costing you the transaction or creating a compliance headache.

This guide explains exactly what a proforma invoice is, when to use it in Nigeria, and how it differs from a tax invoice under FIRS rules.

## What Is a Proforma Invoice?

A proforma invoice is a **preliminary document** that looks like an invoice but is not a formal demand for payment and carries no legal obligation to pay. It is essentially a confirmed quote — a statement from the seller saying: *"Here is what I plan to deliver, and here is what it will cost. Do you agree?"*

The word "proforma" comes from Latin, meaning "as a matter of form." It is a document issued in the form of an invoice before the actual transaction takes place.

**Key point:** A proforma invoice does not record a completed sale. It is not entered into your accounts as income, and your client does not record it as an accounts payable liability.

## Proforma Invoice vs Tax Invoice: The Core Differences

| | **Proforma Invoice** | **Tax Invoice** |
|---|---|---|
| **When issued** | Before the sale / before delivery | After delivery of goods or services |
| **Purpose** | Confirm terms; request approval | Formally request payment |
| **Creates payment obligation** | No | Yes |
| **VAT applicable** | No (not a real sale yet) | Yes (for VAT-registered businesses) |
| **Recorded in accounts** | No | Yes (accounts receivable) |
| **FIRS compliance required** | No | Yes |
| **Can buyer claim input VAT** | No | Yes |

## When to Use a Proforma Invoice in Nigeria

### 1. Before Starting a Project

A Nigerian marketing agency presents a proforma invoice to a new client before work begins. The client reviews the quoted services and prices, approves the document, and pays a deposit — at which point the agency issues a proper tax invoice for the deposit amount.

**Example:**
> Vivid Communications issues Proforma Invoice #PI-2026-003 to Lagos Breweries Ltd:
> - Brand campaign strategy: ₦300,000
> - Video production (2 × 60-second clips): ₦450,000
> - Media buying budget management: ₦120,000
> - **Estimated Total: ₦870,000**
>
> *This proforma invoice is for approval purposes only. A tax invoice will be issued upon commencement of services.*

Lagos Breweries approves the proforma, pays a 50% deposit (₦435,000), and Vivid raises Tax Invoice #INV-2026-041 for that amount.

### 2. For Import and Export Documentation

Proforma invoices are widely used in Nigerian import/export to satisfy customs requirements before goods physically cross the border. The Nigerian Customs Service accepts proforma invoices for pre-shipment documentation and Letters of Credit (LC). Once the goods are delivered, a commercial tax invoice replaces the proforma.

### 3. For Requesting Advance Payments or Deposits

When you need a client to pay upfront before work begins, a proforma invoice formalises the request without creating a completed-sale record. Once the payment arrives, raise a proper tax invoice.

### 4. When Prices Are Subject to Change

If your prices may vary based on final scope, material costs, or exchange rates, a proforma invoice lets you present indicative pricing without locking both parties into a final obligation.

### 5. Government and Corporate Procurement

Many Nigerian government ministries, departments, and agencies (MDAs) and large corporates require a proforma invoice during their purchase approval process, before raising a purchase order (LPO). The LPO then triggers the supply, after which you issue a tax invoice.

## What to Include on a Proforma Invoice

Because a proforma invoice is not a FIRS-regulated document, there are no statutory mandatory fields. However, include the following to make it useful and professional:

- The words **"PROFORMA INVOICE"** clearly at the top (this distinguishes it from a tax invoice)
- A proforma reference number (separate series from your tax invoices — e.g. PI-2026-001)
- Issue date and expiry date (proforma quotes should have a validity period — typically 14 to 30 days)
- Your business name, address, and contact details
- Client name and address
- Itemised description of goods or services
- Quantities and estimated unit prices
- Estimated total (in ₦)
- A validity statement: *"Prices quoted are valid for 14 days from the date of this proforma invoice"*
- A note that VAT will apply on the final tax invoice (if you are VAT-registered)

**What to leave out:**
- A TIN or VAT registration number is not required (though including your TIN does no harm)
- Do not calculate or show VAT — the sale has not occurred yet
- Do not use a sequential tax invoice number — keep a separate proforma numbering series

## Converting a Proforma Invoice to a Tax Invoice

Once the client approves the proforma and work is delivered (or goods dispatched), you issue a proper tax invoice:

1. Create a new document with a tax invoice number from your sequential series
2. Confirm final prices (update any that changed from the proforma)
3. Add your TIN and VAT registration number
4. Calculate VAT at 7.5% on taxable items
5. Reference the original proforma: *"Ref: Proforma Invoice #PI-2026-003"*

The proforma becomes a historical document; the tax invoice is the one that matters for payment and FIRS compliance.

## Common Proforma Invoice Mistakes

- **Calling it an invoice without the "proforma" label** — this creates confusion about whether payment is due
- **Including VAT on a proforma** — VAT is only applicable on a completed supply; adding it to a proforma is premature
- **Using tax invoice numbers for proformas** — keep the numbering series completely separate
- **Not including an expiry date** — open-ended proformas create disputes when prices change

## Create Both Documents in Minutes

[InvoiceGenerator.ng](/invoice-generator-nigeria) lets you generate professional proforma invoices and FIRS-compliant tax invoices quickly, with all the right fields for each document type. For a complete guide to Nigerian invoicing requirements — including when each document type is appropriate — visit the [InvoiceGenerator.ng invoicing guide](/guide).

---

*Need to send a professional proforma invoice or tax invoice today? Try [InvoiceGenerator.ng](/invoice-generator-nigeria) — free, no sign-up required.*`,
    },
];

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    console.log('Seeding batch 2 blog posts (3 posts)...\n');

    let author = await prisma.user.findFirst({ where: { isAdmin: true } });
    if (!author) {
        console.log('No admin user found — checking for any user...');
        author = await prisma.user.findFirst();
    }
    if (!author) {
        console.error('❌  No users found. Please sign up in the app first.');
        process.exit(1);
    }

    if (author.name !== 'Olivia S') {
        author = await prisma.user.update({
            where: { id: author.id },
            data: { name: 'Olivia S' },
        });
    }

    console.log(`Author: ${author.name} (${author.email})\n`);

    for (const post of posts) {
        const result = await prisma.blogPost.upsert({
            where: { slug: post.slug },
            update: { ...post, authorId: author.id },
            create: { ...post, authorId: author.id },
        });
        console.log(`✅  ${result.title}`);
        console.log(`    /blog/${result.slug}\n`);
    }

    console.log('Done — 3 posts live.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
        await pool.end();
    });
